window.AHH_T = {
  fr: {
    'hero.badge': 'Communauté Haïtienne · Hamilton, ON',
    'hero.intro': "Notre communauté s'appuie sur des valeurs essentielles :",
    'hero.values': 'Liberté · Égalité · Entraide',
    'hero.subtitle': "et l'union comme source de notre puissance.",
    'hero.sub': "Main dans la main, créons l'endroit que nous avons toujours espéré.",
    'hero.btn1': 'Voir nos activités',
    'hero.btn2': 'Nous rejoindre',
    'stat.membres': 'Membres actifs',
    'stat.activites': 'Activités',
    'stat.benevoles': 'Heures de bénévolat',
    'stat.annees': 'Années de service',
    'why.badge': 'Avantages',
    'why.h2': "Pourquoi rejoindre l'AHH ?",
    'why1.h3': 'Réseau communautaire',
    'why1.p': 'Connectez-vous avec des familles haïtiennes de Hamilton et de la région.',
    'why2.h3': 'Culture & traditions',
    'why2.p': 'Célébrez la richesse culturelle haïtienne à travers nos événements et activités.',
    'why3.h3': 'Opportunités',
    'why3.p': "Accédez à des stages, formations et offres d'emploi pour la communauté.",
    'why4.h3': 'Entraide & soutien',
    'why4.p': "Bénéficiez d'un réseau d'entraide pour les nouvelles familles arrivant au Canada.",
    'members.join1': 'Rejoignez',
    'members.join2': 'membres actifs de la communauté AHH',
    'members.cta': 'Nous rejoindre →',
    'pillars.badge': 'Notre mission',
    'pillars.h2': 'Trois piliers qui nous unissent',
    'pillars.desc': 'AHH repose sur :',
    'pillar1.h3': 'Réseautage & Connexions',
    'pillar1.p': 'Créer des espaces de rencontre pour que les familles haïtiennes de Hamilton se connectent, partagent et bâtissent des liens durables.',
    'pillar1.link': 'Voir les activités →',
    'pillar2.h3': 'Événements culturels',
    'pillar2.p': 'Organiser des événements vibrants pour célébrer la richesse de la culture haïtienne et renforcer notre identité commune.',
    'pillar2.link': 'Voir la galerie →',
    'pillar3.h3': "Programmes d'assistance",
    'pillar3.p': "Offrir un soutien adapté aux familles haïtiennes — nouveaux arrivants, ressources d'intégration et réseau de solidarité.",
    'pillar3.link': 'Rejoindre AHH →',
    'test.badge': 'Témoignages',
    'test.h2': 'Ce que dit notre communauté',
    'team.badge': 'Leadership',
    'team.h2': 'Notre équipe dirigeante',
    'team.p': 'Des bénévoles engagés au service de la communauté depuis janvier 2008.',
    'about.h1': "À propos d'AHH",
    'about.p1': 'Notre histoire, notre mission et les valeurs qui nous animent depuis notre fondation en janvier 2008.',
    'about.who.badge': 'Qui sommes-nous',
    'about.who.h2': 'Une association au service de la communauté haïtienne',
    'about.mission.badge': 'Mission & Valeurs',
    'about.mission.h2': 'Ce qui nous guide',
    'about.mission.p': 'Notre mission repose sur trois piliers fondamentaux et des valeurs ancrées dans notre identité haïtienne.',
    'val.liberte.h3': 'Liberté',
    'val.egalite.h3': 'Égalité',
    'val.entraide.h3': 'Entraide',
    'val.culture.h3': 'Culture',
    'val.resilience.h3': 'Résilience',
    'val.espoir.h3': 'Espoir',
    'about.hist.badge': 'Notre histoire',
    'about.hist.h2': "18 ans de croissance et d'engagement",
    'tl.2009.title': "Fondation d'AHH",
    'tl.2010.title': 'Premières années — Construction des bases',
    'tl.2014.title': 'Croissance et structuration',
    'tl.2018.title': 'Expansion communautaire',
    'tl.2022.title': 'Rayonnement et reconnaissance',
    'tl.2026.title': "✨ Aujourd'hui — 18 ans d'engagement",
    'about.part.badge': 'Partenaires',
    'about.part.h2': 'Ceux qui nous soutiennent',
    'about.part.p': "AHH collabore avec des organisations locales partageant nos valeurs d'inclusion et de soutien communautaire.",
    'about.who.p1': "L'Association Haïtienne de Hamilton (AHH) est un organisme communautaire à but non lucratif fondé en <strong>janvier 2008</strong> pour rassembler, soutenir et célébrer la communauté haïtienne établie dans la région de Hamilton, Ontario.",
    'about.who.p2': "Nous croyons que chaque famille mérite un espace où elle se sent comprise, valorisée et connectée à ses racines culturelles, tout en s'intégrant pleinement dans la société canadienne.",
    'about.who.p3': "Notre association est gouvernée par un comité exécutif élu par les membres et opère dans le respect des lois de l'Ontario régissant les organismes sans but lucratif.",
    'val.liberte.p': "Nous défendons le droit de chaque membre à s'exprimer, participer et s'épanouir librement au sein de notre communauté.",
    'val.egalite.p': 'Chaque membre, quelle que soit sa situation, bénéficie du même accès aux ressources, activités et opportunités offertes par AHH.',
    'val.entraide.p': 'La solidarité est au cœur de notre action. Nous nous soutenons mutuellement dans les moments difficiles comme dans les célébrations.',
    'val.culture.p': 'Nous préservons et célébrons la richesse de la culture haïtienne : langue, gastronomie, musique, art et traditions.',
    'val.resilience.p': "Héritiers d'une nation qui a su surmonter l'adversité, nous incarnons la force et la persévérance dans tout ce que nous faisons.",
    'val.espoir.p': "Nous construisons aujourd'hui l'avenir que nos enfants et les générations futures méritent : inclusif, prospère et épanoui.",
    'tl.2009.text': "Un groupe de familles haïtiennes se rassemble pour créer un espace d'entraide et de célébration culturelle à Hamilton, Ontario.",
    'tl.2010.text': 'Premiers événements culturels publics, célébration du 1er janvier haïtien, premiers repas communautaires et collectes de fonds.',
    'tl.2014.text': 'Mise en place d\'une structure formelle avec présidente, vice-président, trésorière, secrétaire et délégués élus par les membres.',
    'tl.2018.text': "AHH atteint plus de 80 membres actifs et lance ses programmes d'assistance aux nouveaux arrivants haïtiens à Hamilton.",
    'tl.2022.text': 'Plus de 120 membres, 52 événements annuels, 300+ heures de bénévolat et lancement du portail numérique ahhamilton.ca.',
    'tl.2026.text': "AHH continue de grandir et de servir la communauté haïtienne de Hamilton avec la même passion et la même détermination qu'en janvier 2008.",
    'about.badge17': '🇭🇹 18 ans au service de la communauté · janvier 2008 – 2026',
    'about.becomePartner': 'Devenez partenaire',
    'adh.h1': 'Rejoindre AHH',
    'adh.p1': "Devenez membre et faites partie d'une communauté unie, active et bienveillante.",
    'adh.plans.badge': 'Adhésion',
    'adh.plans.h2': 'Choisissez votre membership',
    'adh.plans.p': "Toutes les formules incluent l'accès aux activités et l'appartenance à notre communauté.",
    'mem.free.period': 'Membres de base',
    'mem.free.btn': 'Adhérer gratuitement',
    'mem.bien.badge': 'Le plus populaire',
    'mem.bien.period': 'par mois · $100/an',
    'mem.bien.btn': 'Devenir bienfaiteur',
    'mem.part.period': 'par mois · $200/an',
    'mem.part.btn': 'Devenir partenaire',
    'adh.form.badge': 'Inscription',
    'adh.form.h2': "Remplissez votre demande d'adhésion",
    'adh.form.h3': "Formulaire d'adhésion",
    'step1.title': 'Remplissez le formulaire',
    'step2.title': 'Confirmation par courriel',
    'step3.title': 'Bienvenue dans la communauté !',
    'act.h1': 'Activités & Événements',
    'act.p1': 'Découvrez nos prochains rassemblements et revivez nos moments passés.',
    'act.upcoming.badge': 'À venir',
    'act.upcoming.h2': 'Prochains événements',
    'act.upcoming.p': 'Rejoignez-nous pour ces moments de partage, culture et solidarité.',
    'act.past.badge': 'Archives',
    'act.past.h2': 'Événements passés',
    'act.cta.h2': 'Vous voulez participer ?',
    'act.cta.p': "Inscrivez-vous comme membre pour vous inscrire à nos événements et accéder au portail membre.",
    'act.cta.btn': 'Devenir membre',
    'gal.h1': 'Nos moments ensemble',
    'gal.p1': 'Des souvenirs précieux de nos rassemblements, célébrations et activités communautaires.',
    'gal.badge': 'Nos photos',
    'gal.h2': 'Galerie communautaire',
    'gal.desc': "Chaque image raconte l'histoire d'une communauté soudée, vivante et rayonnante.",
    'gal.recent.h3': '📸 Photos récentes',
    'gal.recent.p': 'Nos dernières activités et événements',
    'gal.archive.h3': '🏛️ Archives',
    'gal.archive.p': 'Photos historiques de nos activités',
    'gal.videos.badge': 'Vidéos',
    'gal.videos.h2': 'Nos moments en vidéo',
    'gal.videos.p': 'Revivez nos événements et activités communautaires.',
    'gal.cat.general': 'Général',
    'gal.cat.culturel': 'Événements culturels',
    'gal.cat.repas': 'Repas & Rassemblements',
    'gal.cat.benevolat': 'Bénévolat',
    'gal.cat.reunion': 'Réunions',
    'gal.photo': 'photo',
    'gal.photos': 'photos',
    'gal.clickToView': 'cliquer pour voir',
    'gal.watchYoutube': 'Voir sur YouTube →',
    'tal.h1': 'Nos talents communautaires',
    'tal.p1': 'Découvrez les professionnels et artisans de la communauté haïtienne de Hamilton.',
    'tal.cta.h2': 'Vous êtes un professionnel ?',
    'tal.cta.p': 'Partagez votre expertise avec la communauté. Créez votre fiche talent dans le portail membre.',
    'tal.cta.btn': 'Créer ma fiche',
    'ann.h1': 'Petites annonces',
    'ann.p1': 'Vendez, donnez et échangez entre membres de la communauté AHH.',
    'ann.cta.h2': 'Vous avez quelque chose à vendre ou à donner ?',
    'ann.cta.p': "Les membres avec un plan bienfaiteur ($10/mois) peuvent publier des annonces. Contactez l'administration ou connectez-vous à votre espace membre.",
    'ann.cta.btn': 'Devenir bienfaiteur',
    'ann.myspace': 'Mon espace membre →',
    'ann.priceTbd': 'Prix à discuter',
    'ann.empty': "Aucune annonce pour l'instant.",
    'ann.loadError': 'Impossible de charger les annonces.',
    'footer-desc': 'Association Haïtienne de Hamilton, une communauté unie dans la culture et la solidarité.',
    'footer-copy': '© 2026 AHH | Association Haïtienne de Hamilton. Tous droits réservés.',
    'casl.text': '🍪 Ce site utilise des témoins (cookies) essentiels à son fonctionnement, conformément à la <strong>Loi canadienne anti-pourriel (LCAP/CASL)</strong>. En continuant à naviguer, vous acceptez notre <a href="/privacy.html">politique de confidentialité</a>.',
    'casl.accept': 'Accepter',
    'casl.decline': 'Refuser',
  },

  en: {
    // ── index.html ─────────────────────────────────────────────────────────
    'hero.badge': 'Haitian Community · Hamilton, ON',
    'hero.intro': 'Our community is built on essential values:',
    'hero.values': 'Freedom · Equality · Solidarity',
    'hero.subtitle': 'and unity as the source of our strength.',
    'hero.sub': "Hand in hand, let's create the place we always hoped for.",
    'hero.btn1': 'See our activities',
    'hero.btn2': 'Join us',
    'stat.membres': 'Active Members',
    'stat.activites': 'Activities',
    'stat.benevoles': 'Volunteer Hours',
    'stat.annees': 'Years of Service',
    'why.badge': 'Benefits',
    'why.h2': 'Why join AHH?',
    'why1.h3': 'Community Network',
    'why1.p': 'Connect with Haitian families from Hamilton and the surrounding area.',
    'why2.h3': 'Culture & Traditions',
    'why2.p': 'Celebrate the richness of Haitian culture through our events and activities.',
    'why3.h3': 'Opportunities',
    'why3.p': 'Access internships, training and job opportunities for the community.',
    'why4.h3': 'Mutual Aid & Support',
    'why4.p': 'Benefit from a support network for new families arriving in Canada.',
    'members.join1': 'Join',
    'members.join2': 'active members of the AHH community',
    'members.cta': 'Join us →',
    'cd.next': 'Next event:',
    'cd.days': 'days',
    'cd.hours': 'hours',
    'cd.min': 'min',
    'cd.sec': 'sec',
    'welcome.h2': 'Welcome to the AHH community!',
    'welcome.p1': 'Haitian Association of Hamilton: culture, solidarity and mutual aid since 2008.',
    'welcome.p2': 'Join our growing community. Access activities, cultural events and the Haitian-Canadian support network.',
    'welcome.btn1': 'Become a member →',
    'welcome.btn2': 'Explore the site',
    'featured.badge': '⭐ FEATURED',
    'link.allActivities': 'See all activities →',
    'feed.badge': 'Live',
    'feed.h2': 'Upcoming activities',
    'feed.p': "Stay connected to your community's events.",
    'galprev.badge': 'Gallery',
    'galprev.h2': 'Our best moments',
    'galprev.p': 'A window into the life and culture of our community.',
    'galprev.link': 'See the full gallery →',
    'videos.badge': 'Our videos',
    'videos.h2': 'Relive our moments',
    'videos.p': 'Discover our events and activities on video.',
    'sponsors.badge': 'Partners',
    'sponsors.h2': 'Our sponsors',
    'sponsors.p': "Thank you to those who support the mission of the Haitian Association of Hamilton.",
    'don.badge': 'Support AHH',
    'don.h2': 'Contribute to our mission',
    'don.p': 'Your donation funds our activities, supports families and celebrates Haitian culture in Hamilton.',
    'don.toggle': '🔄 Monthly donation',
    'don.label1': 'Friend',
    'don.desc1': 'Covers the cost of a community activity.',
    'don.give10': 'Give $10',
    'don.popular': 'Popular',
    'don.label2': 'Benefactor',
    'don.desc2': 'Supports a family settling in Hamilton.',
    'don.give50': 'Give $50',
    'don.label3': 'Partner',
    'don.desc3': 'Sponsors a cultural event or community project.',
    'don.give100': 'Give $100',
    'don.label4': 'Custom amount',
    'don.desc4': 'Choose the amount that suits you. Every dollar counts!',
    'don.giveGeneric': 'Give',
    'don.giveAmount': 'Give $',
    'don.toggleActive': '✅ Monthly mode active, click to return to a one-time donation',
    'don.monthlyAmount': 'Monthly donation $',
    'don.perMonth': '/month',
    'don.minAmount': 'Please enter a minimum amount of $1.',
    'don.emailPrompt': 'Your email (optional):',
    'don.error': 'Error',
    'don.connError': 'Connection error',
    'amb.badge': '⭐ Honor',
    'amb.h2': 'Ambassador <span class="italic-accent">of the month</span>',
    'amb.p': 'Every month, we celebrate an outstanding member of our community.',
    'amb.crown': '👑 Ambassador of the month',
    'tl.badge': 'Our history',
    'tl.h2': 'AHH since <span class="italic-accent-blue">2008</span>',
    'tl.p': "More than 17 years of solidarity, culture and commitment to the Haitian community of Hamilton.",
    'tl1.h4': 'Founding of AHH',
    'tl1.p': 'A group of Haitian families in Hamilton comes together to create a community association rooted in the values of mutual aid and solidarity.',
    'tl2.h4': 'First major cultural events',
    'tl2.p': 'Organization of the first Haitian cultural evenings in Hamilton, celebrating music, cuisine and the traditions of the Haitian people.',
    'tl3.h4': 'Newcomer assistance program',
    'tl3.p': 'Launch of a structured integration support program for Haitian families newly arrived in Canada.',
    'tl4.h4': 'Digital transition',
    'tl4.p': "Facing the pandemic, AHH innovates by moving its activities online, strengthening community ties despite the distance.",
    'tl5.h4': 'AHH digital platform',
    'tl5.p': 'Launch of the complete online platform: member management, events, tickets, payments and communications — a first in the region.',
    'tl6.h4': 'Growth and outreach',
    'tl6.p': 'AHH keeps growing, innovating and reaching further, with a community more united than ever around Haitian and Canadian values.',
    'info.badge': '🇭🇹 Haiti',
    'info.h2': 'Haiti in numbers',
    'info.p': 'The Pearl of the Antilles, a nation rich in history, culture and resilience.',
    'info1.label': "First independent Black republic in the world",
    'info2.label': 'Inhabitants on the island',
    'info3.label': 'Official languages: French and Haitian Creole',
    'info4.label': 'Years of musical history (Rara, Kompa, Jazz)',
    'info5.label': 'National dish: fried pork served with banann peze',
    'info6.label': 'Year the blue and red Haitian flag was created',
    'faq.badge': 'Frequently asked questions',
    'faq.h2': 'Everything you want to <span class="highlight">know</span>',
    'faq.p': 'Answers to the most common questions about AHH.',
    'faq1.q': 'How do I become an AHH member?',
    'faq1.a': 'You can become a member by filling out our <a href="adhesion.html" style="color:var(--g2);font-weight:600">online membership form</a>. Membership is open to anyone interested in the Haitian community of Hamilton. A confirmation email will be sent to you after approval.',
    'faq2.q': 'What is the cost of annual membership?',
    'faq2.a': 'Membership cost varies by plan. We offer a free basic plan, as well as Benefactor and Partner plans for those who want to support our activities further. All details are on the membership page.',
    'faq3.q': 'How do I register for an activity or event?',
    'faq3.a': 'Check out our <a href="actualites.html" style="color:var(--g2);font-weight:600">activities page</a> and click on the event you\'re interested in. If the event has a fee, you can purchase your tickets directly online through our secure Stripe payment system.',
    'faq4.q': 'How do I make a donation to the association?',
    'faq4.a': 'You can donate directly from our <a href="#don" style="color:var(--g2);font-weight:600">Donations section</a> at the bottom of the home page. We accept secure online payments via Stripe. Every contribution, small or large, helps our community grow.',
    'faq5.q': "I'm a newly arrived Haitian in Hamilton — how can AHH help me?",
    'faq5.a': 'AHH offers a support program for newcomers: orientation, integration resources, access to the community network and administrative support. Contact us via our <a href="#contact" style="color:var(--g2);font-weight:600">contact form</a> or by phone.',
    'faq6.q': 'How do I join the AHH WhatsApp group?',
    'faq6.a': 'Click the green WhatsApp button at the bottom right of the page, or contact Jean Raymond Antoine directly at 905-519-7967. The group is open to all active members of the Haitian community of Hamilton.',
    'nl.h2': 'Stay informed',
    'nl.p': 'Receive our news, invitations and announcements directly in your inbox. Free, ad-free.',
    'nl.placeholder': 'your@email.com',
    'nl.btn': 'Subscribe',
    'nl.invalidEmail': 'Please enter a valid email.',
    'nl.success': 'Subscription confirmed! Thank you for joining our community.',
    'nl.error': 'Error. Please try again.',
    'nlp.h1': 'Newsletters',
    'nlp.p1': 'The latest news and announcements sent to our community.',
    'nlp.loading': 'Loading…',
    'nlp.subscribe': '📩 Subscribe to receive the next ones',
    'nlp.empty': 'No archived newsletter at the moment.',
    'nlp.error': 'Unable to load newsletters right now.',
    'eq.h1': 'Our leadership team',
    'eq.sub': 'Dedicated people committed to serving the Haitian community of Hamilton.',
    'eq.badge1': 'Executive committee',
    'eq.h2_1': 'Those who guide us',
    'eq.p1': "AHH's team volunteers with heart to build a strong, united and thriving community.",
    'eq.badge2': 'Volunteering',
    'eq.h2_2': 'Join our team',
    'eq.p2': 'Want to contribute to the development of the Haitian community of Hamilton? We warmly welcome any motivated volunteer committed to our values.',
    'eq.h3': "What we're looking for",
    'eq.li1': 'Commitment to the Haitian community',
    'eq.li2': 'Availability for events and meetings',
    'eq.li3': 'Varied skills: organization, communication, finance',
    'eq.li4': 'Team spirit and values of solidarity',
    'com.h1': 'Business map',
    'com.sub': 'Discover businesses and services run by members of our community in Hamilton.',
    'com.cat.tous': 'All',
    'com.cat.construction': '🔨 Construction',
    'com.cat.art': '🎨 Art',
    'com.cat.cuisine': '🍽️ Cuisine',
    'com.cat.beaute': '💅 Beauty',
    'com.cat.technologie': '💻 Technology',
    'com.cat.education': '📚 Education',
    'com.cat.sante': '🏥 Health',
    'com.cat.transport': '🚗 Transport',
    'com.cat.finance': '💰 Finance',
    'com.cat.autre': '✨ Other',
    'com.loading': 'Loading…',
    'com.cta.h2': 'Are you a member who runs a business?',
    'com.cta.p': 'Add it to the map — visible to the whole community after committee review.',
    'com.cta.btn': 'Submit my business →',
    'com.catfull.construction': '🔨 Construction & Renovation',
    'com.catfull.art': '🎨 Art & Creativity',
    'com.catfull.cuisine': '🍽️ Cuisine & Catering',
    'com.catfull.beaute': '💅 Beauty & Wellness',
    'com.catfull.technologie': '💻 Technology & IT',
    'com.catfull.education': '📚 Education & Coaching',
    'com.catfull.sante': '🏥 Health & Fitness',
    'com.catfull.transport': '🚗 Transport & Delivery',
    'com.catfull.finance': '💰 Finance & Accounting',
    'com.catfull.autre': '✨ Other',
    'com.emptyCat': 'No business in this category at the moment.',
    'com.website': 'Website',
    'com.loadError': 'Unable to load businesses right now.',
    'fi.h1': '🏆 Wall of Pride',
    'fi.sub': "Pitit tig se tig — let's celebrate every one of our members' successes with the whole community.",
    'fi.badge': 'Our successes',
    'fi.h2_1': 'Community achievements',
    'fi.p1': 'Every individual success is a collective pride.',
    'fi.f.diplome': '🎓 Diplomas',
    'fi.f.emploi': '💼 Employment',
    'fi.f.arts': '🎨 Arts & Culture',
    'fi.f.sport': '⚽ Sports',
    'fi.f.entreprise': '🚀 Entrepreneurship',
    'fi.f.communaute': '🤝 Community',
    'fi.loading': '⏳ Loading…',
    'fi.h3': 'Share your success!',
    'fi.p2': 'Did you or a family member accomplish something remarkable? Send us your story — we are proud of all our members.',
    'fi.submit': 'Submit an achievement',
    'fi.h2_2': 'Our community in numbers',
    'fi.p3': 'The strength of the Haitian diaspora of Hamilton',
    'fi.stat2': 'University graduates per year',
    'fi.stat3': 'Entrepreneurs in the community',
    'fi.stat4': 'Year AHH was founded',
    'fi.badge.diplome': '🎓 Diploma',
    'fi.badge.emploi': '💼 Employment',
    'fi.badge.arts': '🎨 Arts',
    'fi.badge.sport': '⚽ Sports',
    'fi.badge.entreprise': '🚀 Entrepreneurship',
    'fi.badge.communaute': '🤝 Community',
    'fi.empty': "No achievement published yet.<br/>Contact us to submit yours!",
    'fi.loadError': 'Unable to load achievements.',
    'real.h1': 'Our achievements',
    'real.sub': 'Since our founding in 2008, AHH has been building a strong, united and committed community in Hamilton.',
    'real.stat2': 'Activities organized',
    'real.stat4': "Years of history",
    'real.cta.h2': 'Be part of the story',
    'real.cta.p': 'Join the Haitian Association of Hamilton and help build our community.',
    'real.cta.btn': 'Become a member',
    'real.ev1.title': 'Founding of AHH',
    'real.ev1.desc': 'Official creation of the Haitian Association of Hamilton by a group of committed citizens of the Haitian community.',
    'real.ev2.title': 'First members',
    'real.ev2.desc': 'Recruitment of the first founding members and establishment of the executive committee (president, secretary, treasurer, delegates).',
    'real.ev3.title': 'First community events',
    'real.ev3.desc': 'Organization of the first cultural and social activities to bring the Haitian community of Hamilton together.',
    'real.ev4.title': 'Launch of the digital platform',
    'real.ev4.desc': 'Launch of the ahhamilton.ca website with dashboard, ticketing, digital membership card and management tools.',
    'real.ev5.title': 'Digital membership cards',
    'real.ev5.desc': 'Rollout of membership cards with QR code, photo verification and a unified scanner for events.',
    'real.ev6.title': 'Jobs and internships portal',
    'real.ev6.desc': 'Automatic integration of job postings in Hamilton via Adzuna, with committee approval before publication.',
    'real.ev7.title': 'Mobile PWA app',
    'real.ev7.desc': 'Launch of the progressive web app (PWA) enabling offline access, notifications and scanning from the phone.',
    'real.ev8.title': 'Community growth',
    'real.ev8.desc': 'AHH reaches 50+ active members and regularly organizes cultural events, workshops and networking activities.',
    'contact.badge': 'Contact',
    'contact.h2': 'Write to us',
    'contact.p': "We're happy to welcome you. Contact us with any questions.",
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'cf.title': 'Send us a message',
    'cf.sentH3': 'Message sent!',
    'cf.sentP': "Thank you for contacting us. We'll reply as soon as possible.",
    'cf.name': 'Full name',
    'cf.email': 'Email',
    'cf.subject': 'Subject',
    'cf.subject.choose': 'Choose a subject…',
    'cf.subject.general': 'General information',
    'cf.subject.adhesion': 'Membership',
    'cf.subject.benevolat': 'Volunteering',
    'cf.subject.evenements': 'Events',
    'cf.subject.partenariat': 'Partnership',
    'cf.subject.autre': 'Other',
    'cf.adhesionNotice': 'To become an AHH member, use our dedicated form:<a href="adhesion.html" style="color:#1b5e20;font-weight:700;display:block;margin-top:6px">→ Membership form</a>',
    'cf.message': 'Message',
    'cf.message.placeholder': 'How can we help you?',
    'cf.submit': 'Send message',
    'cf.privacyNote': 'Your data is processed according to our <a href="privacy.html" style="color:var(--g2)">privacy policy</a>.',
    'cf.sending': 'Sending…',
    'cf.serverError': 'Server error',
    'cf.sendError': 'Error sending message.',
    'cf.fillRequired': 'Please fill in all required fields.',
    'bday.today': 'Today',
    'bday.h2': 'Happy birthday!',
    'bday.p': 'The whole AHH family wishes you a wonderful celebration 🥳',
    'ef.h1': '👨‍👩‍👧 Family Space',
    'ef.sub': 'For children born here and parents building their life in Hamilton — together.',
    'ef.badge1': 'Activities',
    'ef.h2_1': 'Programs by age group',
    'ef.tab1': '👶 0–5 years',
    'ef.tab2': '🧒 6–12 years',
    'ef.tab3': '👦 13–17 years',
    'ef.tab4': '👪 Parents',
    'ef.reflexion': '💭 In development',
    'ef.c1.h3': 'Creole story time',
    'ef.c1.p': 'Every Saturday morning. Haitian stories read in Creole and French for toddlers. A moment of cultural connection from the earliest age.',
    'ef.c2.h3': 'Haitian songs and nursery rhymes',
    'ef.c2.p': 'Monthly music sessions with drums and Creole instruments. Babies learn Haitian rhythms naturally.',
    'ef.c3.h3': "Moms' group",
    'ef.c3.p': 'Bi-monthly gatherings for new Haitian mothers — sharing experiences, emotional support and advice in Creole and French.',
    'ef.c4.h3': 'Homework help',
    'ef.c4.p': 'Every Wednesday after school, AHH volunteer members help children with their homework. Free for members.',
    'ef.c5.h3': 'Creole arts workshop',
    'ef.c5.p': 'Painting, crafts and artistic expression inspired by Haitian culture. Art as a bridge between here and Haiti.',
    'ef.c6.h3': 'Mini sports tournaments',
    'ef.c6.p': 'Soccer, basketball and traditional Haitian games. To get kids moving and build friendships in the community.',
    'ef.c7.h3': 'Haitian history club',
    'ef.c7.p': "Monthly workshops so our children learn Haiti's history, from the 1804 independence to today.",
    'ef.c8.h3': 'Academic mentoring',
    'ef.c8.p': "Matched with professional adult members based on the teen's interests — health, engineering, law, arts. To prepare for career choices.",
    'ef.c9.h3': 'Resume and interview workshop',
    'ef.c9.p': 'To land a first student job. Resume writing, mock interviews, practical advice tailored to the local market.',
    'ef.c10.h3': 'Youth Space',
    'ef.c10.p': 'The group for ages 15-30. Cultural outings, discussions, community leadership. A space to be young and proudly Haitian in Hamilton.',
    'ef.c11.h3': 'Navigating the school system',
    'ef.c11.p': "How to get involved in your children's school, understand HWDSB/HWCDSB report cards, talk with teachers, parents' rights.",
    'ef.c12.h3': 'French and English classes',
    'ef.c12.p': 'Free resources to improve your written French or everyday English — to better help your children and succeed at work.',
    'ef.c13.h3': 'Scholarships',
    'ef.c13.p': 'AHH compiles scholarships available for children of the Haitian community. Contact us for the up-to-date list.',
    'ef.c14.h3': "Youth mental health",
    'ef.c14.p': 'How to talk to your Canadian-born children about their dual identity. Resources in Creole, French and English for the mental health of 2nd-generation immigrant youth.',
    'ef.badge2': 'Resources',
    'ef.h2_2': 'Services for families in Hamilton',
    'ef.r1.h4': 'Hamilton Public Library',
    'ef.r1.p': "Free programs for children, library card, English classes. hamilton.ca/library",
    'ef.r2.h4': 'Good Shepherd Hamilton',
    'ef.r2.p': 'Family services, food assistance, support for newcomers. goodshepherd.ca',
    'ef.r3.h4': 'Settlement & Integration Services',
    'ef.r3.p': 'Integration support, language classes, school orientation for newcomers. hamiltonimmigrant.ca',
    'ef.r4.h4': 'Community health centre',
    'ef.r4.p': 'Pediatric care, maternal health, services in multiple languages. hamiltonchs.ca',
    'ef.r5.h4': 'Best Start Hamilton',
    'ef.r5.p': 'Programs for parents of children 0-6 years: toy lending, home visits, play groups.',
    'ef.r6.h4': 'HWDSB (public school board)',
    'ef.r6.p': 'English public schools. hwdsb.on.ca — ELL family services available.',
    'ef.h2_3': 'Questions from parents',
    'ef.qa1.q': "My child refuses to speak Creole at home. How can I encourage them?",
    'ef.qa1.a': 'This is very common among 2nd-generation children — they want to fit in and fear being different. A few ideas: make Creole fun (games, songs), involve grandparents by video, show that you\'re proud to speak Creole in public. The <a href="creole.html">Learn Creole</a> page has rhymes and phrases to practice together.',
    'ef.qa2.q': 'How do I enroll my child in a school in Hamilton?',
    'ef.qa2.a': 'Go to hwdsb.on.ca (English public school) or HWCDSB (Catholic). Bring: proof of address, birth certificate, immunization record, previous report card if available. The school board offers a newcomer welcome program. AHH can help you prepare your documents.',
    'ef.qa3.q': 'My child born in Haiti needs their schooling recognized. How do I do that?',
    'ef.qa3.a': 'HWDSB offers a placement assessment to determine the appropriate grade. For secondary studies, contact the Ontario Ministry of Education equivalency office. Settlement Services can accompany you through this process for free.',
    'ef.qa4.q': 'What scholarships exist for Haitian students in Canada?',
    'ef.qa4.a': 'Several organizations offer scholarships to children of the diaspora: the Fondation Haïti Canada, some Canadian universities have funds for racialized students, and the federal government has programs for children of immigrants. Contact AHH — we maintain an up-to-date list of available scholarships and can help you fill out applications.',
    'ef.qa5.q': "My teen struggles with identity — not quite Haitian, not quite Canadian. What can I do?",
    'ef.qa5.a': "This identity struggle is very common and often experienced alone. AHH's Youth Space group creates a space where 15-30 year-olds share exactly these experiences. Connections with peers living the same reality are often more helpful than any parental advice. Don't hesitate to also consult a therapist trained in immigration issues — several offer services in French in Hamilton.",
    'ef.h2_4': 'Your family is part of our family',
    'ef.cta.p': "Family Space activities are free for AHH members. Join today and give your children a community.",
    'ef.cta.btn': 'Join — $20/year',
    'pillars.badge': 'Our Mission',
    'pillars.h2': 'Three pillars that unite us',
    'pillars.desc': 'AHH is built on:',
    'pillar1.h3': 'Networking & Connections',
    'pillar1.p': 'Creating meeting spaces so Haitian families in Hamilton can connect, share and build lasting bonds.',
    'pillar1.link': 'See activities →',
    'pillar2.h3': 'Cultural Events',
    'pillar2.p': 'Organizing vibrant events to celebrate the richness of Haitian culture and strengthen our common identity.',
    'pillar2.link': 'See gallery →',
    'pillar3.h3': 'Assistance Programs',
    'pillar3.p': 'Providing tailored support to Haitian families — newcomers, integration resources and solidarity network.',
    'pillar3.link': 'Join AHH →',
    'test.badge': 'Testimonials',
    'test.h2': 'What our community says',
    'team.badge': 'Leadership',
    'team.h2': 'Our leadership team',
    'team.p': 'Dedicated volunteers serving the community since January 2008.',
    'Présidente': 'President',
    'Vice-Président': 'Vice-President',
    'Trésorière': 'Treasurer',
    'Secrétaire': 'Secretary',
    'Délégué': 'Accompanier',
    'Conseiller': 'Advisor',

    // ── about.html ─────────────────────────────────────────────────────────
    'about.h1': 'About AHH',
    'about.p1': 'Our history, mission and the values that have driven us since our founding in January 2008.',
    'about.who.badge': 'Who we are',
    'about.who.h2': 'An association serving the Haitian community',
    'about.mission.badge': 'Mission & Values',
    'about.mission.h2': 'What guides us',
    'about.mission.p': 'Our mission rests on three fundamental pillars and values rooted in our Haitian identity.',
    'val.liberte.h3': 'Freedom',
    'val.egalite.h3': 'Equality',
    'val.entraide.h3': 'Solidarity',
    'val.culture.h3': 'Culture',
    'val.resilience.h3': 'Resilience',
    'val.espoir.h3': 'Hope',
    'about.hist.badge': 'Our history',
    'about.hist.h2': '17 years of growth and commitment',
    'tl.2009.title': 'AHH Founded',
    'tl.2010.title': 'First years — Building foundations',
    'tl.2014.title': 'Growth and structuring',
    'tl.2018.title': 'Community expansion',
    'tl.2022.title': 'Outreach and recognition',
    'tl.2026.title': '✨ Today — 17 years of commitment',
    'about.part.badge': 'Partners',
    'about.part.h2': 'Those who support us',
    'about.part.p': 'AHH collaborates with local organizations sharing our values of inclusion and community support.',
    'about.who.p1': 'The Haitian Association of Hamilton (AHH) is a non-profit community organization founded in <strong>January 2008</strong> to bring together, support and celebrate the Haitian community established in the Hamilton, Ontario area.',
    'about.who.p2': 'We believe every family deserves a space where they feel understood, valued and connected to their cultural roots, while fully integrating into Canadian society.',
    'about.who.p3': 'Our association is governed by an executive committee elected by the members and operates in compliance with Ontario laws governing non-profit organizations.',
    'val.liberte.p': "We defend every member's right to express themselves, participate and thrive freely within our community.",
    'val.egalite.p': 'Every member, regardless of their situation, has the same access to the resources, activities and opportunities offered by AHH.',
    'val.entraide.p': 'Solidarity is at the heart of our action. We support each other in difficult times as well as in celebrations.',
    'val.culture.p': 'We preserve and celebrate the richness of Haitian culture: language, cuisine, music, art and traditions.',
    'val.resilience.p': 'Heirs of a nation that has overcome adversity, we embody strength and perseverance in everything we do.',
    'val.espoir.p': 'We are building today the future that our children and future generations deserve: inclusive, prosperous and thriving.',
    'tl.2009.text': 'A group of Haitian families comes together to create a space for mutual aid and cultural celebration in Hamilton, Ontario.',
    'tl.2010.text': "First public cultural events, celebration of Haitian Independence Day (Jan. 1st), first community meals and fundraisers.",
    'tl.2014.text': 'Establishment of a formal structure with president, vice-president, treasurer, secretary and delegates elected by the members.',
    'tl.2018.text': "AHH reaches over 80 active members and launches its support programs for newly arrived Haitians in Hamilton.",
    'tl.2022.text': 'Over 120 members, 52 annual events, 300+ volunteer hours and launch of the ahhamilton.ca digital portal.',
    'tl.2026.text': 'AHH continues to grow and serve the Haitian community of Hamilton with the same passion and determination as in January 2008.',
    'about.badge17': '🇭🇹 18 years serving the community · January 2008 – 2026',
    'about.becomePartner': 'Become a partner',
    'Devenir partenaire →': 'Become a partner →',

    // ── adhesion.html ──────────────────────────────────────────────────────
    'adh.h1': 'Join AHH',
    'adh.p1': 'Become a member and be part of a united, active and caring community.',
    'adh.plans.badge': 'Membership',
    'adh.plans.h2': 'Choose your membership',
    'adh.plans.p': 'All plans include access to activities and belonging to our community.',
    'mem.free.period': 'Basic members',
    'mem.free.btn': 'Join for free',
    'mem.bien.badge': 'Most popular',
    'mem.bien.period': 'per month · $100/year',
    'mem.bien.btn': 'Become a benefactor',
    'mem.part.period': 'per month · $200/year',
    'mem.part.btn': 'Become a partner',
    'adh.form.badge': 'Registration',
    'adh.form.h2': 'Fill out your membership application',
    'adh.form.h3': 'Membership form',
    'Prénom *': 'First name *',
    'Nom *': 'Last name *',
    'Adresse courriel *': 'Email address *',
    'Téléphone': 'Phone',
    'Date de naissance': 'Date of birth',
    'Adresse': 'Address',
    "Type d'adhésion *": 'Membership type *',
    'Comment avez-vous connu AHH ?': 'How did you hear about AHH?',
    'Message (facultatif)': 'Message (optional)',
    "Envoyer ma demande d'adhésion": 'Send my membership application',
    'step1.title': 'Fill out the form',
    'step2.title': 'Email confirmation',
    'step3.title': 'Welcome to the community!',

    // ── actualites.html ────────────────────────────────────────────────────
    'act.h1': 'Activities & Events',
    'act.p1': 'Discover our upcoming gatherings and relive our past moments.',
    'act.upcoming.badge': 'Coming up',
    'act.upcoming.h2': 'Upcoming events',
    'act.upcoming.p': 'Join us for these moments of sharing, culture and solidarity.',
    'act.past.badge': 'Archives',
    'act.past.h2': 'Past events',
    'act.cta.h2': 'Want to participate?',
    'act.cta.p': 'Sign up as a member to register for our events and access the member portal.',
    'act.cta.btn': 'Become a member',
    'Tous': 'All',
    'Culturel': 'Cultural',
    'Bénévolat': 'Volunteer',
    'Réunion': 'Meeting',
    'Sport': 'Sport',
    'Aucun événement trouvé': 'No events found',

    // ── galerie.html ───────────────────────────────────────────────────────
    'gal.h1': 'Our moments together',
    'gal.p1': 'Precious memories of our gatherings, celebrations and community activities.',
    'gal.badge': 'Our photos',
    'gal.h2': 'Community gallery',
    'gal.desc': 'Each image tells the story of a united, vibrant and radiant community.',
    'gal.recent.h3': '📸 Recent photos',
    'gal.recent.p': 'Our latest activities and events',
    'gal.archive.h3': '🏛️ Archives',
    'gal.archive.p': 'Historical photos of our activities',
    'gal.videos.badge': 'Videos',
    'gal.videos.h2': 'Our moments on video',
    'gal.videos.p': 'Relive our community events and activities.',
    'gal.cat.general': 'General',
    'gal.cat.culturel': 'Cultural events',
    'gal.cat.repas': 'Meals & Gatherings',
    'gal.cat.benevolat': 'Volunteering',
    'gal.cat.reunion': 'Meetings',
    'gal.photo': 'photo',
    'gal.photos': 'photos',
    'gal.clickToView': 'click to view',
    'gal.watchYoutube': 'Watch on YouTube →',

    // ── talents.html ───────────────────────────────────────────────────────
    'tal.h1': 'Our community talents',
    'tal.p1': 'Discover the professionals and artisans of the Haitian community in Hamilton.',
    'tal.cta.h2': 'Are you a professional?',
    'tal.cta.p': 'Share your expertise with the community. Create your talent listing in the member portal.',
    'tal.cta.btn': 'Create my listing',
    'Construction': 'Construction',
    'Technologie': 'Technology',
    'Cuisine': 'Cooking',
    'Art & Musique': 'Art & Music',
    'Santé': 'Health',
    'Éducation': 'Education',
    'Aucun talent trouvé': 'No talent found',
    'Rechercher un talent…': 'Search for a talent…',

    // ── annonces.html ──────────────────────────────────────────────────────
    'ann.h1': 'Classifieds',
    'ann.p1': 'Sell, give away and trade with members of the AHH community.',
    'ann.cta.h2': 'Do you have something to sell or give away?',
    'ann.cta.p': 'Members with a Benefactor plan ($10/month) can post listings. Contact the administration or log in to your member area.',
    'ann.cta.btn': 'Become a benefactor',
    'ann.myspace': 'My member area →',
    'ann.priceTbd': 'Price negotiable',
    'ann.empty': 'No listings yet.',
    'ann.loadError': 'Unable to load listings.',
    'Vente': 'Sale',
    'Don': 'Donation',
    'Échange': 'Exchange',
    'Recherche': 'Wanted',
    'Aucune annonce trouvée': 'No listings found',
    'Rechercher une annonce…': 'Search listings…',
    'Gratuit': 'Free',
    'casl.text': '🍪 This site uses cookies essential to its operation, in accordance with Canada\'s Anti-Spam Legislation (<strong>CASL</strong>). By continuing to browse, you accept our <a href="/privacy.html">privacy policy</a>.',
    'casl.accept': 'Accept',
    'casl.decline': 'Decline',
  },

  ht: {
    // ── index.html ─────────────────────────────────────────────────────────
    'hero.badge': 'Kominote Ayisyen · Hamilton, ON',
    'hero.intro': 'Kominote nou an chita sou valè esansyèl yo :',
    'hero.values': 'Libète · Egalite · Solidarite',
    'hero.subtitle': 'ak inite kòm sous fòs nou.',
    'hero.sub': 'Men nan men, ann kreye kote nou te toujou reve a.',
    'hero.btn1': 'Wè aktivite nou yo',
    'hero.btn2': 'Vin jwenn nou',
    'stat.membres': 'Manm aktif',
    'stat.activites': 'Aktivite',
    'stat.benevoles': 'Èdtan bènevolat',
    'stat.annees': 'Ane sèvis',
    'why.badge': 'Avantaj',
    'why.h2': 'Poukisa vin jwenn AHH ?',
    'why1.h3': 'Rezo kominotè',
    'why1.p': 'Konekte ak fanmi ayisyen Hamilton ak rejyon an.',
    'why2.h3': 'Kilti & tradisyon',
    'why2.p': 'Selebre richès kilti ayisyen an atravè evènman ak aktivite nou yo.',
    'why3.h3': 'Opòtinite',
    'why3.p': 'Jwenn aksè a estaj, fòmasyon ak ofri travay pou kominote a.',
    'why4.h3': 'Antrèd & sipò',
    'why4.p': 'Benefisye yon rezo antrèd pou nouvo fanmi k ap rive nan Kanada.',
    'members.join1': 'Vin jwenn',
    'members.join2': 'manm aktif nan kominote AHH la',
    'members.cta': 'Vin jwenn nou →',
    'cd.next': 'Pwochen evènman :',
    'cd.days': 'jou',
    'cd.hours': 'è',
    'cd.min': 'min',
    'cd.sec': 'sek',
    'welcome.h2': 'Byenveni nan kominote AHH la !',
    'welcome.p1': 'Asosyasyon Ayisyen Hamilton : kilti, solidarite ak antrèd depi 2008.',
    'welcome.p2': 'Vin jwenn kominote nou k ap grandi a. Jwenn aksè a aktivite, evènman kiltirèl ak rezo antrèd ayisyen-kanadyen an.',
    'welcome.btn1': 'Vin manm →',
    'welcome.btn2': 'Eksplore sit la',
    'featured.badge': '⭐ AN VEDÈT',
    'link.allActivities': 'Wè tout aktivite yo →',
    'feed.badge': 'An dirèk',
    'feed.h2': 'Pwochen aktivite yo',
    'feed.p': 'Rete konekte ak evènman kominote w la.',
    'galprev.badge': 'Galri',
    'galprev.h2': 'Pi bèl moman nou yo',
    'galprev.p': 'Yon fenèt sou lavi ak kilti kominote nou an.',
    'galprev.link': 'Wè tout galri a →',
    'videos.badge': 'Videyo nou yo',
    'videos.h2': 'Reviv moman nou yo',
    'videos.p': 'Dekouvri evènman ak aktivite nou yo an videyo.',
    'sponsors.badge': 'Patnè',
    'sponsors.h2': 'Konmanditè nou yo',
    'sponsors.p': 'Mèsi a tout moun ki soutni misyon Asosyasyon Ayisyen Hamilton an.',
    'don.badge': 'Soutni AHH',
    'don.h2': 'Kontribye nan misyon nou an',
    'don.p': 'Don ou finanse aktivite nou yo, soutni fanmi yo epi fè kilti ayisyen an briye Hamilton.',
    'don.toggle': '🔄 Don chak mwa',
    'don.label1': 'Zanmi',
    'don.desc1': 'Kouvri frè yon aktivite kominotè.',
    'don.give10': 'Bay $10',
    'don.popular': 'Popilè',
    'don.label2': 'Byenfetè',
    'don.desc2': 'Soutni yon fanmi k ap enstale Hamilton.',
    'don.give50': 'Bay $50',
    'don.label3': 'Patnè',
    'don.desc3': 'Sponsò yon evènman kiltirèl oswa yon pwojè kominotè.',
    'don.give100': 'Bay $100',
    'don.label4': 'Montan lib',
    'don.desc4': 'Chwazi montan ki fè w plezi. Chak dola konte !',
    'don.giveGeneric': 'Bay',
    'don.giveAmount': 'Bay $',
    'don.toggleActive': '✅ Mòd chak mwa aktif, klike pou retounen nan don inik',
    'don.monthlyAmount': 'Don chak mwa $',
    'don.perMonth': '/mwa',
    'don.minAmount': 'Tanpri antre yon montan minimòm 1$.',
    'don.emailPrompt': 'Imèl ou (opsyonèl) :',
    'don.error': 'Erè',
    'don.connError': 'Erè koneksyon',
    'amb.badge': '⭐ Onè',
    'amb.h2': 'Anbasadè <span class="italic-accent">mwa a</span>',
    'amb.p': 'Chak mwa, nou selebre yon manm ekstraòdinè nan kominote nou an.',
    'amb.crown': '👑 Anbasadè mwa a',
    'tl.badge': 'Istwa nou',
    'tl.h2': 'AHH depi <span class="italic-accent-blue">2008</span>',
    'tl.p': 'Plis pase 17 ane solidarite, kilti ak angajman nan sèvis kominote ayisyen Hamilton an.',
    'tl1.h4': 'Fondasyon AHH',
    'tl1.p': 'Yon gwoup fanmi ayisyen Hamilton reyini pou kreye yon asosyasyon kominotè ki chita sou valè antrèd ak solidarite.',
    'tl2.h4': 'Premye gwo evènman kiltirèl yo',
    'tl2.p': 'Òganizasyon premye sware kiltirèl ayisyen Hamilton, ki selebre mizik, kwizin ak tradisyon pèp ayisyen an.',
    'tl3.h4': 'Pwogram asistans pou nouvo arivan yo',
    'tl3.p': 'Lansman yon pwogram estriktire pou ede fanmi ayisyen ki fenk rive Kanada entegre.',
    'tl4.h4': 'Tranzisyon nimerik',
    'tl4.p': 'Fas ak pandemi an, AHH inove lè li òganize aktivite li yo an liy, sa ki ranfòse lyen kominotè yo malgre distans lan.',
    'tl5.h4': 'Platfòm nimerik AHH',
    'tl5.p': 'Lansman platfòm konplè sou entènèt la : jesyon manm, evènman, tikè, peman ak kominikasyon, yon premye nan rejyon an.',
    'tl6.h4': 'Kwasans ak rayonnman',
    'tl6.p': 'AHH kontinye grandi, inove ak briye, ak yon kominote ki pi ini pase janm sou valè ayisyen ak kanadyen yo.',
    'info.badge': '🇭🇹 Ayiti',
    'info.h2': 'Ayiti an chif',
    'info.p': 'Bijou Antiy yo, yon nasyon ki rich an istwa, kilti ak rezistans.',
    'info1.label': 'Premye repiblik nwa endepandan nan mond lan',
    'info2.label': 'Popilasyon sou zile a',
    'info3.label': 'Lang ofisyèl yo : franse ak kreyòl ayisyen',
    'info4.label': 'Ane istwa mizikal (Rara, Konpa, Djaz)',
    'info5.label': 'Manje nasyonal : vyann kochon fri ak bannann peze',
    'info6.label': 'Ane drapo ble ak wouj ayisyen an te kreye',
    'faq.badge': 'Kesyon moun poze souvan',
    'faq.h2': 'Tout sa w vle <span class="highlight">konnen</span>',
    'faq.p': 'Repons a kesyon moun poze pi souvan sou AHH.',
    'faq1.q': 'Kijan pou m vin manm AHH ?',
    'faq1.a': 'Ou ka vin manm lè w ranpli <a href="adhesion.html" style="color:var(--g2);font-weight:600">fòm adezyon anliy nou an</a>. Adezyon an ouvè pou tout moun ki enterese nan kominote ayisyen Hamilton an. Y ap voye yon imèl konfimasyon ba ou apre apwobasyon.',
    'faq2.q': 'Konbyen kotizasyon anyèl la koute ?',
    'faq2.a': 'Kotizasyon an varye selon plan ou chwazi a. Nou ofri yon plan gratis debaz, ansanm ak plan Byenfetè ak Patnè pou moun ki vle soutni aktivite nou yo plis. Tout detay yo sou paj adezyon an.',
    'faq3.q': 'Kijan pou m enskri nan yon aktivite oswa evènman ?',
    'faq3.a': 'Gade <a href="actualites.html" style="color:var(--g2);font-weight:600">paj aktivite</a> nou an epi klike sou evènman ki enterese w la. Si evènman an peye, ou ka achte tikè w yo dirèkteman anliy atravè sistèm peman sekirize Stripe nou an.',
    'faq4.q': 'Kijan pou m fè yon don bay asosyasyon an ?',
    'faq4.a': 'Ou ka fè yon don dirèkteman nan <a href="#don" style="color:var(--g2);font-weight:600">seksyon Don</a> anba paj akèy la. Nou aksepte peman sekirize anliy atravè Stripe. Chak kontribisyon, piti oswa gwo, ede kominote nou an grandi.',
    'faq5.q': 'Mwen se yon nouvo arivan ayisyen Hamilton, kijan AHH ka ede m ?',
    'faq5.a': 'AHH ofri yon pwogram akonpayman pou nouvo arivan yo : oryantasyon, resous entegrasyon, aksè nan rezo kominotè a ak sipò administratif. Kontakte nou atravè <a href="#contact" style="color:var(--g2);font-weight:600">fòm kontak</a> nou an oswa pa telefòn.',
    'faq6.q': 'Kijan pou m antre nan gwoup WhatsApp AHH la ?',
    'faq6.a': 'Klike sou bouton WhatsApp vèt anba adwat paj la, oswa kontakte Jean Raymond Antoine dirèkteman nan 905-519-7967. Gwoup la ouvè pou tout manm aktif kominote ayisyen Hamilton an.',
    'nl.h2': 'Rete enfòme',
    'nl.p': 'Resevwa nouvèl, envitasyon ak anons nou yo dirèkteman nan bwat imèl ou. Gratis, san piblisite.',
    'nl.placeholder': 'imèl@ou.com',
    'nl.btn': 'Abòne',
    'nl.invalidEmail': 'Tanpri antre yon imèl valid.',
    'nl.success': 'Abònman konfime ! Mèsi pou w vin jwenn kominote nou an.',
    'nl.error': 'Erè. Tanpri eseye ankò.',
    'nlp.h1': 'Bilten',
    'nlp.p1': 'Dènye nouvèl ak anons yo voye bay kominote nou an.',
    'nlp.loading': 'K ap chaje…',
    'nlp.subscribe': '📩 Abòne pou resevwa pwochenn yo',
    'nlp.empty': 'Pa gen bilten achive pou kounye a.',
    'nlp.error': 'Enposib pou chaje bilten yo kounye a.',
    'eq.h1': 'Ekip lidèchip nou an',
    'eq.sub': 'Moun angaje ki devwe nan sèvis kominote ayisyen Hamilton an.',
    'eq.badge1': 'Komite egzekitif',
    'eq.h2_1': 'Moun ki gide nou yo',
    'eq.p1': 'Ekip AHH la travay benevòlman ak kè pou bati yon kominote solid, ini ak k ap fleri.',
    'eq.badge2': 'Benevola',
    'eq.h2_2': 'Vin jwenn ekip nou an',
    'eq.p2': 'Ou vle kontribye nan devlopman kominote ayisyen Hamilton an ? Nou akeyi ak kè kontan tout benevòl ki motive ak angaje nan valè nou yo.',
    'eq.h3': 'Sa n ap chèche',
    'eq.li1': 'Angajman anvè kominote ayisyen an',
    'eq.li2': 'Disponibilite pou evènman ak reyinyon',
    'eq.li3': 'Konpetans varye : òganizasyon, kominikasyon, finans',
    'eq.li4': 'Lespri ekip ak valè solidarite',
    'com.h1': 'Kat komès yo',
    'com.sub': 'Dekouvri komès ak sèvis manm kominote nou an jere Hamilton.',
    'com.cat.tous': 'Tout',
    'com.cat.construction': '🔨 Konstriksyon',
    'com.cat.art': '🎨 Atizay',
    'com.cat.cuisine': '🍽️ Kwizin',
    'com.cat.beaute': '💅 Bote',
    'com.cat.technologie': '💻 Teknoloji',
    'com.cat.education': '📚 Edikasyon',
    'com.cat.sante': '🏥 Sante',
    'com.cat.transport': '🚗 Transpò',
    'com.cat.finance': '💰 Finans',
    'com.cat.autre': '✨ Lòt',
    'com.loading': 'K ap chaje…',
    'com.cta.h2': 'Ou se yon manm ki gen yon komès ?',
    'com.cta.p': 'Ajoute l sou kat la — vizib pou tout kominote a apre revizyon komite a.',
    'com.cta.btn': 'Soumèt komès mwen →',
    'com.catfull.construction': '🔨 Konstriksyon & Renovasyon',
    'com.catfull.art': '🎨 Atizay & Kreyativite',
    'com.catfull.cuisine': '🍽️ Kwizin & Trete',
    'com.catfull.beaute': '💅 Bote & Byennèt',
    'com.catfull.technologie': '💻 Teknoloji & Enfòmatik',
    'com.catfull.education': '📚 Edikasyon & Antrènman',
    'com.catfull.sante': '🏥 Sante & Espò',
    'com.catfull.transport': '🚗 Transpò & Livrezon',
    'com.catfull.finance': '💰 Finans & Kontabilite',
    'com.catfull.autre': '✨ Lòt',
    'com.emptyCat': 'Pa gen komès nan kategori sa a kounye a.',
    'com.website': 'Sit entènèt',
    'com.loadError': 'Enposib pou chaje komès yo kounye a.',
    'fi.h1': '🏆 Mi Fyète',
    'fi.sub': 'Pitit tig se tig — ann selebre chak siksè manm nou yo ak tout kominote a.',
    'fi.badge': 'Siksè nou yo',
    'fi.h2_1': 'Reyalizasyon kominote a',
    'fi.p1': 'Chak siksè endividyèl se yon fyète kolektif.',
    'fi.f.diplome': '🎓 Diplòm',
    'fi.f.emploi': '💼 Travay',
    'fi.f.arts': '🎨 Atizay & Kilti',
    'fi.f.sport': '⚽ Espò',
    'fi.f.entreprise': '🚀 Antreprenarya',
    'fi.f.communaute': '🤝 Kominote',
    'fi.loading': '⏳ K ap chaje…',
    'fi.h3': 'Pataje siksè ou !',
    'fi.p2': 'Ou menm oswa yon manm fanmi w reyalize yon bagay remakab ? Voye istwa ou ban nou — nou fyè de tout manm nou yo.',
    'fi.submit': 'Soumèt yon reyalizasyon',
    'fi.h2_2': 'Kominote nou an an chif',
    'fi.p3': 'Fòs dyaspora ayisyen Hamilton an',
    'fi.stat2': 'Diplome inivèsitè chak ane',
    'fi.stat3': 'Antreprenè nan kominote a',
    'fi.stat4': 'Ane AHH te fonde',
    'fi.badge.diplome': '🎓 Diplòm',
    'fi.badge.emploi': '💼 Travay',
    'fi.badge.arts': '🎨 Atizay',
    'fi.badge.sport': '⚽ Espò',
    'fi.badge.entreprise': '🚀 Antreprenarya',
    'fi.badge.communaute': '🤝 Kominote',
    'fi.empty': 'Poko gen reyalizasyon pibliye.<br/>Kontakte nou pou soumèt pa ou !',
    'fi.loadError': 'Enposib pou chaje reyalizasyon yo.',
    'real.h1': 'Reyalizasyon nou yo',
    'real.sub': 'Depi fondasyon nou an 2008, AHH ap bati yon kominote solid, ini ak angaje Hamilton.',
    'real.stat2': 'Aktivite òganize',
    'real.stat4': 'Ane istwa',
    'real.cta.h2': 'Fè pati istwa a',
    'real.cta.p': 'Vin jwenn Asosyasyon Ayisyen Hamilton epi ede bati kominote nou an.',
    'real.cta.btn': 'Vin manm',
    'real.ev1.title': 'Fondasyon AHH',
    'real.ev1.desc': 'Kreyasyon ofisyèl Asosyasyon Ayisyen Hamilton pa yon gwoup sitwayen angaje nan kominote ayisyen an.',
    'real.ev2.title': 'Premye manm yo',
    'real.ev2.desc': 'Rekritman premye manm fondatè yo ak mete an plas komite egzekitif la (prezidan, sekretè, trezorye, delege).',
    'real.ev3.title': 'Premye evènman kominotè yo',
    'real.ev3.desc': 'Òganizasyon premye aktivite kiltirèl ak sosyal pou rasanble kominote ayisyen Hamilton an.',
    'real.ev4.title': 'Lansman platfòm nimerik la',
    'real.ev4.desc': 'Mete sou entènèt sit ahhamilton.ca ak tablo bòd, biyè, kat manm nimerik ak zouti jesyon.',
    'real.ev5.title': 'Kat manm nimerik',
    'real.ev5.desc': 'Deplwaman kat manm ak kòd QR, verifikasyon foto ak yon eskanè inifye pou evènman yo.',
    'real.ev6.title': 'Pòtay travay ak estaj',
    'real.ev6.desc': 'Entegrasyon otomatik ofri travay Hamilton atravè Adzuna, ak apwobasyon komite anvan piblikasyon.',
    'real.ev7.title': 'Aplikasyon mobil PWA',
    'real.ev7.desc': 'Lansman aplikasyon web pwogresif (PWA) ki pèmèt aksè san entènèt, notifikasyon ak eskane depi telefòn.',
    'real.ev8.title': 'Kwasans kominotè',
    'real.ev8.desc': 'AHH rive gen 50+ manm aktif epi òganize regilyèman evènman kiltirèl, atelye ak aktivite rezo.',
    'contact.badge': 'Kontak',
    'contact.h2': 'Ekri nou',
    'contact.p': 'Nou kontan resevwa w. Kontakte nou pou nenpòt kesyon.',
    'contact.address': 'Adrès',
    'contact.phone': 'Telefòn',
    'contact.email': 'Imèl',
    'cf.title': 'Voye yon mesaj ba nou',
    'cf.sentH3': 'Mesaj voye !',
    'cf.sentP': 'Mèsi paske w kontakte nou. N ap reponn ou pi vit posib.',
    'cf.name': 'Non konplè',
    'cf.email': 'Imèl',
    'cf.subject': 'Sijè',
    'cf.subject.choose': 'Chwazi yon sijè…',
    'cf.subject.general': 'Enfòmasyon jeneral',
    'cf.subject.adhesion': 'Adezyon',
    'cf.subject.benevolat': 'Benevola',
    'cf.subject.evenements': 'Evènman',
    'cf.subject.partenariat': 'Patenarya',
    'cf.subject.autre': 'Lòt',
    'cf.adhesionNotice': 'Pou vin manm AHH, itilize fòm dedye nou an :<a href="adhesion.html" style="color:#1b5e20;font-weight:700;display:block;margin-top:6px">→ Fòm adezyon</a>',
    'cf.message': 'Mesaj',
    'cf.message.placeholder': 'Kijan nou ka ede w ?',
    'cf.submit': 'Voye mesaj la',
    'cf.privacyNote': 'Done ou yo trete selon <a href="privacy.html" style="color:var(--g2)">politik konfidansyalite</a> nou an.',
    'cf.sending': 'Voye ap fèt…',
    'cf.serverError': 'Erè sèvè',
    'cf.sendError': 'Erè pandan l ap voye.',
    'cf.fillRequired': 'Tanpri ranpli tout chan obligatwa yo.',
    'bday.today': 'Jodi a',
    'bday.h2': 'Bòn fèt !',
    'bday.p': 'Gran fanmi AHH la swete w yon bèl fèt 🥳',
    'ef.h1': '👨‍👩‍👧 Espas Fanmi',
    'ef.sub': 'Pou timoun ki fèt isit ak paran k ap bati lavi yo Hamilton — ansanm.',
    'ef.badge1': 'Aktivite',
    'ef.h2_1': 'Pwogram pa gwoup laj',
    'ef.tab1': '👶 0–5 an',
    'ef.tab2': '🧒 6–12 an',
    'ef.tab3': '👦 13–17 an',
    'ef.tab4': '👪 Paran',
    'ef.reflexion': '💭 Ap devlope',
    'ef.c1.h3': 'Lè istwa an kreyòl',
    'ef.c1.p': 'Chak samdi maten. Istwa ayisyen li an kreyòl ak fransè pou tibebe yo. Yon moman koneksyon kiltirèl depi laj byen jèn.',
    'ef.c2.h3': 'Chante ak ti chante ayisyen',
    'ef.c2.p': 'Sesyon mizik chak mwa ak tanbou ak enstriman kreyòl. Bebe yo aprann rit ayisyen yo natirèlman.',
    'ef.c3.h3': 'Gwoup manman yo',
    'ef.c3.p': 'Rankont de fwa pa mwa pou nouvo manman ayisyen — pataje eksperyans, sipò emosyonèl ak konsèy an kreyòl ak fransè.',
    'ef.c4.h3': 'Èd nan devwa',
    'ef.c4.p': 'Chak mèkredi apre lekòl, benevòl manm AHH ede timoun yo fè devwa yo. Gratis pou manm yo.',
    'ef.c5.h3': 'Atelye atizay kreyòl',
    'ef.c5.p': 'Penti, atizana ak ekspresyon atistik enspire pa kilti ayisyen an. Atizay kòm yon pon ant isit ak Ayiti.',
    'ef.c6.h3': 'Mini-tounwa espòtif',
    'ef.c6.p': 'Foutbòl, baskètbòl ak jwèt tradisyonèl ayisyen. Pou fè timoun yo bouje epi kreye amitye nan kominote a.',
    'ef.c7.h3': 'Klib istwa ayisyen',
    'ef.c7.p': 'Atelye chak mwa pou timoun nou yo konnen istwa Ayiti, depi endepandans 1804 rive jodi a.',
    'ef.c8.h3': 'Mantora akademik',
    'ef.c8.p': 'Jimèl ak manm adilt pwofesyonèl selon enterè adolesan an — sante, jeni, dwa, atizay. Pou prepare chwa karyè.',
    'ef.c9.h3': 'Atelye CV ak antrevi',
    'ef.c9.p': 'Pou jwenn premye travay etidyan. Ekri CV, similasyon antrevi, konsèy pratik ki adapte a mache lokal la.',
    'ef.c10.h3': 'Espas Jèn',
    'ef.c10.p': 'Gwoup pou 15-30 an. Sòti kiltirèl, diskisyon, lidèchip kominotè. Yon espas pou jèn ki fyè dèt ayisyen Hamilton.',
    'ef.c11.h3': 'Navige sistèm lekòl la',
    'ef.c11.p': 'Kijan pou enplike w nan lekòl pitit ou, konprann bilten HWDSB/HWCDSB, pale ak pwofesè yo, dwa paran yo.',
    'ef.c12.h3': 'Kou franse ak anglè',
    'ef.c12.p': 'Resous gratis pou amelyore franse ekri ou oswa anglè chak jou ou — pou pi byen ede pitit ou epi reyisi nan travay.',
    'ef.c13.h3': 'Bous detid',
    'ef.c13.p': 'AHH konpile bous ki disponib pou timoun kominote ayisyen an. Kontakte nou pou lis ajou a.',
    'ef.c14.h3': 'Sante mantal jèn yo',
    'ef.c14.p': 'Kijan pou pale ak pitit ou ki fèt isit sou doub idantite yo. Resous an kreyòl, fransè ak anglè pou sante mantal jèn imigran 2yèm jenerasyon yo.',
    'ef.badge2': 'Resous',
    'ef.h2_2': 'Sèvis pou fanmi Hamilton',
    'ef.r1.h4': 'Bibliyotèk piblik Hamilton',
    'ef.r1.p': 'Pwogram gratis pou timoun, kat bibliyotèk, kou anglè. hamilton.ca/library',
    'ef.r2.h4': 'Good Shepherd Hamilton',
    'ef.r2.p': 'Sèvis familyal, èd alimantè, sipò pou nouvo arivan. goodshepherd.ca',
    'ef.r3.h4': 'Settlement & Integration Services',
    'ef.r3.p': 'Èd entegrasyon, kou lang, oryantasyon eskolè pou nouvo arivan. hamiltonimmigrant.ca',
    'ef.r4.h4': 'Sant sante kominotè',
    'ef.r4.p': 'Swen pedyatrik, sante matènèl, sèvis nan plizyè lang. hamiltonchs.ca',
    'ef.r5.h4': 'Best Start Hamilton',
    'ef.r5.p': 'Pwogram pou paran timoun 0-6 an : prete jwèt, vizit lakay, gwoup jwèt.',
    'ef.r6.h4': 'HWDSB (konsèy eskolè piblik)',
    'ef.r6.p': 'Lekòl piblik anglofòn. hwdsb.on.ca — Sèvis pou fanmi ELL disponib.',
    'ef.h2_3': 'Kesyon paran yo',
    'ef.qa1.q': 'Pitit mwen refize pale kreyòl lakay. Kijan pou m ankouraje l ?',
    'ef.qa1.a': 'Sa se yon bagay ki trè komen pami timoun 2yèm jenerasyon — yo vle entegre epi yo pè yo diferan. Kèk lide : fè kreyòl la amizan (jwèt, chante), enplike granparan yo an videyo, montre ou fyè pale kreyòl an piblik. Paj <a href="creole.html">Aprann kreyòl la</a> gen ti chante ak fraz pou pratike ansanm.',
    'ef.qa2.q': 'Kijan pou m enskri pitit mwen nan yon lekòl Hamilton ?',
    'ef.qa2.a': 'Ale sou hwdsb.on.ca (lekòl piblik anglofòn) oswa HWCDSB (katolik). Pote : prèv adrès, batistè, kanè vaksinasyon, dènye bilten si w genyen l. Konsèy eskolè a ofri yon pwogram akèy pou nouvo arivan yo. AHH ka ede w prepare dokiman ou yo.',
    'ef.qa3.q': 'Pitit mwen ki fèt Ayiti bezwen fè rekonèt akizisyon eskolè li yo. Kijan pou m fè sa ?',
    'ef.qa3.a': 'HWDSB ofri yon evalyasyon plasman pou detèmine ane apwopriye a. Pou etid segondè, kontakte biwo ekivalans Ministè Edikasyon Ontario a. Settlement Services ka akonpaye w nan demach sa a gratis.',
    'ef.qa4.q': 'Ki bous ki egziste pou etidyan ayisyen Kanada ?',
    'ef.qa4.a': 'Plizyè òganizasyon ofri bous bay timoun dyaspora a : Fondasyon Ayiti Kanada, kèk inivèsite kanadyen gen fon pou etidyan rasyalize, epi gouvènman federal la gen pwogram pou timoun imigran. Kontakte AHH — nou kenbe yon lis ajou bous ki disponib epi nou ka ede w ranpli dosye yo.',
    'ef.qa5.q': 'Adolesan mwen ap soufri ak idantite l — ni vrèman ayisyen ni vrèman kanadyen. Kisa pou m fè ?',
    'ef.qa5.a': 'Deplayman idantite sa a trè komen epi souvan viv poukont li. Gwoup Espas Jèn AHH la kreye yon espas kote jèn 15-30 an pataje egzakteman eksperyans sa yo. Koneksyon ak lòt jèn k ap viv menm reyalite a souvan ede plis pase nenpòt konsèy paran. Pa ezite tou konsilte yon terapis ki fòme nan pwoblèm imigrasyon — plizyè ofri sèvis an fransè Hamilton.',
    'ef.h2_4': 'Fanmi ou fè pati fanmi nou',
    'ef.cta.p': 'Aktivite Espas Fanmi yo gratis pou manm AHH. Vin manm jodi a epi bay pitit ou yon kominote.',
    'ef.cta.btn': 'Vin manm — $20/an',
    'pillars.badge': 'Misyon nou',
    'pillars.h2': 'Twa poto ki ini nou',
    'pillars.desc': 'AHH chita sou :',
    'pillar1.h3': 'Rezo & Koneksyon',
    'pillar1.p': 'Kreye espas rankont pou fanmi ayisyen nan Hamilton ka konekte, pataje ak bati lyen dirab.',
    'pillar1.link': 'Wè aktivite yo →',
    'pillar2.h3': 'Evènman kiltirèl',
    'pillar2.p': 'Òganize evènman vibran pou selebre richès kilti ayisyen an ak ranfòse idantite nou ansanm.',
    'pillar2.link': 'Wè galri a →',
    'pillar3.h3': 'Pwogram asistans',
    'pillar3.p': 'Bay sipò adapte pou fanmi ayisyen yo — nouvo rive, resous entegrasyon ak rezo solidarite.',
    'pillar3.link': 'Vin jwenn AHH →',
    'test.badge': 'Temwayaj',
    'test.h2': 'Sa kominote nou an di',
    'team.badge': 'Lidèchip',
    'team.h2': 'Ekip lidèchip nou an',
    'team.p': 'Bènèvòl angaje nan sèvis kominote a depi 2009.',
    'Présidente': 'Prezidante',
    'Vice-Président': 'Vis-Prezidan',
    'Trésorière': 'Trezorye',
    'Secrétaire': 'Sekretè',
    'Délégué': 'Akonpanatè',
    'Accompagnateur': 'Akonpanatè',
    'Conseiller': 'Konseye',

    // ── about.html ─────────────────────────────────────────────────────────
    'about.h1': 'Sou AHH',
    'about.p1': 'Istwa nou, misyon nou ak valè ki gide nou depi fondayson nou an an 2009.',
    'about.who.badge': 'Ki nou ye',
    'about.who.h2': 'Yon asosyasyon nan sèvis kominote ayisyen an',
    'about.mission.badge': 'Misyon & Valè',
    'about.mission.h2': 'Sa ki gide nou',
    'about.mission.p': 'Misyon nou repoze sou twa poto fondamantal ak valè ki anrasinen nan idantite ayisyen nou.',
    'val.liberte.h3': 'Libète',
    'val.egalite.h3': 'Egalite',
    'val.entraide.h3': 'Solidarite',
    'val.culture.h3': 'Kilti',
    'val.resilience.h3': 'Rezilyans',
    'val.espoir.h3': 'Espwa',
    'about.hist.badge': 'Istwa nou',
    'about.hist.h2': '17 ane kwasans ak angajman',
    'tl.2009.title': 'Fondayson AHH',
    'tl.2010.title': 'Premye ane — Bati fondasyon yo',
    'tl.2014.title': 'Kwasans ak estriktirasyon',
    'tl.2018.title': 'Ekspansyon kominotè',
    'tl.2022.title': 'Rayonnman ak rekonesans',
    'tl.2026.title': '✨ Jodi a — 17 ane angajman',
    'about.part.badge': 'Patnè',
    'about.part.h2': 'Moun ki sipòte nou',
    'about.part.p': 'AHH kolabore ak òganizasyon lokal ki pataje valè nou yo sou enklizyon ak sipò kominotè.',
    'about.who.p1': 'Asosyasyon Ayisyen Hamilton (AHH) se yon òganizasyon kominotè san bi likratif ki fonde an <strong>janvye 2008</strong> pou rasanble, sipòte epi selebre kominote ayisyen ki etabli nan rejyon Hamilton, Ontario a.',
    'about.who.p2': 'Nou kwè chak fanmi merite yon espas kote yo santi yo konprann, valorize ak konekte ak rasin kiltirèl yo, pandan y ap entegre nèt nan sosyete kanadyen an.',
    'about.who.p3': 'Asosyasyon nou an gouvène pa yon komite egzekitif manm yo eli epi li opere respekte lwa Ontario ki gouvène òganizasyon san bi likratif yo.',
    'val.liberte.p': "Nou defann dwa chak manm genyen pou eksprime tèt yo, patisipe ak eklouri lib nan kominote nou an.",
    'val.egalite.p': 'Chak manm, kèlkeswa sitiyasyon yo, jwenn menm aksè a resous, aktivite ak opòtinite AHH ofri.',
    'val.entraide.p': 'Solidarite se kè aksyon nou. Nou soutni youn lòt nan moman difisil kou nan selebrasyon.',
    'val.culture.p': 'Nou prezève epi selebre richès kilti ayisyen an : lang, gastwonomi, mizik, atizay ak tradisyon.',
    'val.resilience.p': 'Eritye yon nasyon ki konn simonte advèsite, nou reprezante fòs ak pèsevrans nan tout sa nou fè.',
    'val.espoir.p': "Jodi a, n ap bati avni pitit nou yo ak jenerasyon k ap vini yo merite : yon avni enklizif, pwospè ak k ap fleri.",
    'tl.2009.text': "Yon gwoup fanmi ayisyen reyini pou kreye yon espas antrèd ak selebrasyon kiltirèl Hamilton, Ontario.",
    'tl.2010.text': 'Premye evènman kiltirèl piblik yo, selebrasyon 1ye janvye ayisyen an, premye manje kominotè ak kolekt lajan.',
    'tl.2014.text': 'Mete an plas yon estrikti fòmèl ak prezidant, vis-prezidan, trezorye, sekretè ak delege manm yo eli.',
    'tl.2018.text': 'AHH rive gen plis pase 80 manm aktif epi lanse pwogram asistans pou nouvo arivan ayisyen Hamilton.',
    'tl.2022.text': 'Plis pase 120 manm, 52 evènman chak ane, 300+ èdtan benevola ak lansman pòtay nimerik ahhamilton.ca.',
    'tl.2026.text': 'AHH kontinye grandi epi sèvi kominote ayisyen Hamilton ak menm pasyon ak menm detèminasyon depi janvye 2008.',
    'about.badge17': '🇭🇹 18 ane nan sèvis kominote a · janvye 2008 – 2026',
    'about.becomePartner': 'Vin patnè',
    'Devenir partenaire →': 'Vin patnè →',

    // ── adhesion.html ──────────────────────────────────────────────────────
    'adh.h1': 'Vin jwenn AHH',
    'adh.p1': 'Vin manm epi fè pati yon kominote ini, aktif ak atansyone.',
    'adh.plans.badge': 'Manmbachip',
    'adh.plans.h2': 'Chwazi manmbachip ou',
    'adh.plans.p': 'Tout plan yo enkli aksè nan aktivite yo ak apartenans nan kominote nou an.',
    'mem.free.period': 'Manm debaz',
    'mem.free.btn': 'Vin manm gratis',
    'mem.bien.badge': 'Pi popilè',
    'mem.bien.period': 'pa mwa · $100/ane',
    'mem.bien.btn': 'Vin bienfektè',
    'mem.part.period': 'pa mwa · $200/ane',
    'mem.part.btn': 'Vin patnè',
    'adh.form.badge': 'Enskripsyon',
    'adh.form.h2': 'Ranpli aplikasyon manmbachip ou',
    'adh.form.h3': 'Fòm manmbachip',
    'Prénom *': 'Prenon *',
    'Nom *': 'Non *',
    'Adresse courriel *': 'Adrès imèl *',
    'Téléphone': 'Telefòn',
    'Date de naissance': 'Dat nesans',
    'Adresse': 'Adrès',
    "Type d'adhésion *": 'Tip manmbachip *',
    'Comment avez-vous connu AHH ?': 'Kijan ou te konnen AHH?',
    'Message (facultatif)': 'Mesaj (opsyonèl)',
    "Envoyer ma demande d'adhésion": 'Voye demann manmbachip mwen',
    'step1.title': 'Ranpli fòm nan',
    'step2.title': 'Konfirmasyon pa imèl',
    'step3.title': 'Byenveni nan kominote a!',

    // ── actualites.html ────────────────────────────────────────────────────
    'act.h1': 'Aktivite & Evènman',
    'act.p1': 'Dekouvri rasanbleman kap vini yo epi reviv moman pase nou yo.',
    'act.upcoming.badge': 'Ap vini',
    'act.upcoming.h2': 'Evènman kap vini',
    'act.upcoming.p': 'Vin jwenn nou pou moman pataj, kilti ak solidarite sa yo.',
    'act.past.badge': 'Achiv',
    'act.past.h2': 'Evènman pase yo',
    'act.cta.h2': 'Ou vle patisipe?',
    'act.cta.p': 'Enskri kòm manm pou ou ka enskri nan evènman nou yo epi jwenn aksè nan pòtal manm nan.',
    'act.cta.btn': 'Vin manm',
    'Tous': 'Tout',
    'Culturel': 'Kiltirèl',
    'Bénévolat': 'Bènèvolat',
    'Réunion': 'Reyinyon',
    'Sport': 'Spò',
    'Aucun événement trouvé': 'Pa gen evènman jwenn',

    // ── galerie.html ───────────────────────────────────────────────────────
    'gal.h1': 'Moman nou ansanm',
    'gal.p1': 'Souvni presye rasanbleman, selebrasyon ak aktivite kominotè nou yo.',
    'gal.badge': 'Foto nou yo',
    'gal.h2': 'Galri kominotè',
    'gal.desc': 'Chak imaj rakonte istwa yon kominote ini, vivan ak rayonnant.',
    'gal.recent.h3': '📸 Foto resan',
    'gal.recent.p': 'Dènye aktivite ak evènman nou yo',
    'gal.archive.h3': '🏛️ Achiv',
    'gal.archive.p': 'Foto istorik aktivite nou yo',
    'gal.videos.badge': 'Videyo',
    'gal.videos.h2': 'Moman nou yo an videyo',
    'gal.videos.p': 'Reviv evènman ak aktivite kominotè nou yo.',
    'gal.cat.general': 'Jeneral',
    'gal.cat.culturel': 'Evènman kiltirèl',
    'gal.cat.repas': 'Manje & Rasanbleman',
    'gal.cat.benevolat': 'Benevola',
    'gal.cat.reunion': 'Reyinyon',
    'gal.photo': 'foto',
    'gal.photos': 'foto',
    'gal.clickToView': 'klike pou wè',
    'gal.watchYoutube': 'Gade sou YouTube →',

    // ── talents.html ───────────────────────────────────────────────────────
    'tal.h1': 'Talan kominotè nou yo',
    'tal.p1': 'Dekouvri pwofesyonèl ak atisan kominote ayisyen an nan Hamilton.',
    'tal.cta.h2': 'Ou se yon pwofesyonèl?',
    'tal.cta.p': 'Pataje ekspètiz ou ak kominote a. Kreye afi talan ou nan pòtal manm nan.',
    'tal.cta.btn': 'Kreye afi mwen',
    'Construction': 'Konstriksyon',
    'Technologie': 'Teknoloji',
    'Cuisine': 'Kwizin',
    'Art & Musique': 'Art & Mizik',
    'Santé': 'Sante',
    'Éducation': 'Edikasyon',
    'Aucun talent trouvé': 'Pa gen talan jwenn',
    'Rechercher un talent…': 'Chèche yon talan…',

    // ── annonces.html ──────────────────────────────────────────────────────
    'ann.h1': 'Piti anonn',
    'ann.p1': 'Vann, bay ak echanje ant manm kominote AHH la.',
    'ann.cta.h2': 'Ou gen yon bagay pou vann oswa pou bay ?',
    'ann.cta.p': 'Manm ki gen plan Byenfetè ($10/mwa) ka pibliye anonn. Kontakte administrasyon an oswa konekte nan espas manm ou.',
    'ann.cta.btn': 'Vin Byenfetè',
    'ann.myspace': 'Espas manm mwen →',
    'ann.priceTbd': 'Pri pou diskite',
    'ann.empty': 'Pa gen anonn pou kounye a.',
    'ann.loadError': 'Enposib pou chaje anonn yo.',
    'Vente': 'Lavant',
    'Don': 'Don',
    'Échange': 'Echanj',
    'Recherche': 'Rechèch',
    'Aucune annonce trouvée': 'Pa gen anonn jwenn',
    'Rechercher une annonce…': 'Chèche anonn…',
    'Gratuit': 'Gratis',
    'casl.text': '🍪 Sit sa a itilize temwen (cookies) ki esansyèl pou fonksyònman li, dapre <strong>Lwa kanadyen kont pouryèl (LCAP/CASL)</strong>. Si w kontinye navige, ou aksepte <a href="/privacy.html">politik konfidansyalite</a> nou an.',
    'casl.accept': 'Aksepte',
    'casl.decline': 'Refize',
  }
};
