window.AHH_T = {
  fr: {
    'hero.badge': 'Communauté Haïtienne · Hamilton, ON',
    'hero.intro': "Notre communauté s'appuie sur des valeurs essentielles :",
    'hero.values': 'Liberté · Égalité · Entraide',
    'hero.subtitle': "et l'union comme source de notre puissance.",
    'hero.sub': "Main dans la main, créons l'endroit que nous avons toujours espéré.",
    'hero.btn1': 'Voir nos activités',
    'hero.btn2': 'Nous rejoindre',
    'stat.membres': 'Membres actifs',
    'stat.activites': 'Activités',
    'stat.benevoles': 'Heures de bénévolat',
    'stat.annees': 'Années de service',
    'why.badge': 'Avantages',
    'why.h2': "Pourquoi rejoindre l'AHH ?",
    'why1.h3': 'Réseau communautaire',
    'why1.p': 'Connectez-vous avec des familles haïtiennes de Hamilton et de la région.',
    'why2.h3': 'Culture & traditions',
    'why2.p': 'Célébrez la richesse culturelle haïtienne à travers nos événements et activités.',
    'why3.h3': 'Opportunités',
    'why3.p': "Accédez à des stages, formations et offres d'emploi pour la communauté.",
    'why4.h3': 'Entraide & soutien',
    'why4.p': "Bénéficiez d'un réseau d'entraide pour les nouvelles familles arrivant au Canada.",
    'members.join1': 'Rejoignez',
    'members.join2': 'membres actifs de la communauté AHH',
    'members.cta': 'Nous rejoindre →',
    'pillars.badge': 'Notre mission',
    'pillars.h2': 'Trois piliers qui nous unissent',
    'pillars.desc': 'AHH repose sur :',
    'pillar1.h3': 'Réseautage & Connexions',
    'pillar1.p': 'Créer des espaces de rencontre pour que les familles haïtiennes de Hamilton se connectent, partagent et bâtissent des liens durables.',
    'pillar1.link': 'Voir les activités →',
    'pillar2.h3': 'Événements culturels',
    'pillar2.p': 'Organiser des événements vibrants pour célébrer la richesse de la culture haïtienne et renforcer notre identité commune.',
    'pillar2.link': 'Voir la galerie →',
    'pillar3.h3': "Programmes d'assistance",
    'pillar3.p': "Offrir un soutien adapté aux familles haïtiennes — nouveaux arrivants, ressources d'intégration et réseau de solidarité.",
    'pillar3.link': 'Rejoindre AHH →',
    'test.badge': 'Témoignages',
    'test.h2': 'Ce que dit notre communauté',
    'team.badge': 'Leadership',
    'team.h2': 'Notre équipe dirigeante',
    'team.p': 'Des bénévoles engagés au service de la communauté depuis janvier 2008.',
    'about.h1': "À propos d'AHH",
    'about.p1': 'Notre histoire, notre mission et les valeurs qui nous animent depuis notre fondation en janvier 2008.',
    'about.who.badge': 'Qui sommes-nous',
    'about.who.h2': 'Une association au service de la communauté haïtienne',
    'about.mission.badge': 'Mission & Valeurs',
    'about.mission.h2': 'Ce qui nous guide',
    'about.mission.p': 'Notre mission repose sur trois piliers fondamentaux et des valeurs ancrées dans notre identité haïtienne.',
    'val.liberte.h3': 'Liberté',
    'val.egalite.h3': 'Égalité',
    'val.entraide.h3': 'Entraide',
    'val.culture.h3': 'Culture',
    'val.resilience.h3': 'Résilience',
    'val.espoir.h3': 'Espoir',
    'about.hist.badge': 'Notre histoire',
    'about.hist.h2': "18 ans de croissance et d'engagement",
    'tl.2009.title': "Fondation d'AHH",
    'tl.2010.title': 'Premières années — Construction des bases',
    'tl.2014.title': 'Croissance et structuration',
    'tl.2018.title': 'Expansion communautaire',
    'tl.2022.title': 'Rayonnement et reconnaissance',
    'tl.2026.title': "✨ Aujourd'hui — 18 ans d'engagement",
    'about.part.badge': 'Partenaires',
    'about.part.h2': 'Ceux qui nous soutiennent',
    'about.part.p': "AHH collabore avec des organisations locales partageant nos valeurs d'inclusion et de soutien communautaire.",
    'adh.h1': 'Rejoindre AHH',
    'adh.p1': "Devenez membre et faites partie d'une communauté unie, active et bienveillante.",
    'adh.plans.badge': 'Adhésion',
    'adh.plans.h2': 'Choisissez votre membership',
    'adh.plans.p': "Toutes les formules incluent l'accès aux activités et l'appartenance à notre communauté.",
    'mem.free.period': 'Membres de base',
    'mem.free.btn': 'Adhérer gratuitement',
    'mem.bien.badge': 'Le plus populaire',
    'mem.bien.period': 'par mois · $100/an',
    'mem.bien.btn': 'Devenir bienfaiteur',
    'mem.part.period': 'par mois · $200/an',
    'mem.part.btn': 'Devenir partenaire',
    'adh.form.badge': 'Inscription',
    'adh.form.h2': "Remplissez votre demande d'adhésion",
    'adh.form.h3': "Formulaire d'adhésion",
    'step1.title': 'Remplissez le formulaire',
    'step2.title': 'Confirmation par courriel',
    'step3.title': 'Bienvenue dans la communauté !',
    'act.h1': 'Activités & Événements',
    'act.p1': 'Découvrez nos prochains rassemblements et revivez nos moments passés.',
    'act.upcoming.badge': 'À venir',
    'act.upcoming.h2': 'Prochains événements',
    'act.upcoming.p': 'Rejoignez-nous pour ces moments de partage, culture et solidarité.',
    'act.past.badge': 'Archives',
    'act.past.h2': 'Événements passés',
    'act.cta.h2': 'Vous voulez participer ?',
    'act.cta.p': "Inscrivez-vous comme membre pour vous inscrire à nos événements et accéder au portail membre.",
    'act.cta.btn': 'Devenir membre',
    'gal.h1': 'Nos moments ensemble',
    'gal.p1': 'Des souvenirs précieux de nos rassemblements, célébrations et activités communautaires.',
    'gal.badge': 'Nos photos',
    'gal.h2': 'Galerie communautaire',
    'gal.desc': "Chaque image raconte l'histoire d'une communauté soudée, vivante et rayonnante.",
    'gal.recent.h3': '📸 Photos récentes',
    'gal.recent.p': 'Nos dernières activités et événements',
    'gal.archive.h3': '🏛️ Archives',
    'gal.archive.p': 'Photos historiques de nos activités',
    'tal.h1': 'Nos talents communautaires',
    'tal.p1': 'Découvrez les professionnels et artisans de la communauté haïtienne de Hamilton.',
    'tal.cta.h2': 'Vous êtes un professionnel ?',
    'tal.cta.p': 'Partagez votre expertise avec la communauté. Créez votre fiche talent dans le portail membre.',
    'tal.cta.btn': 'Créer ma fiche',
    'ann.h1': 'Petites annonces',
    'ann.p1': 'Achetez, vendez, donnez ou échangez au sein de la communauté.',
    'ann.cta.h2': 'Vous voulez publier une annonce ?',
    'ann.cta.p': 'Les membres peuvent publier leurs annonces depuis le portail membre. Rejoignez-nous !',
    'ann.cta.btn': 'Devenir membre',
    'footer-desc': 'Association Haïtienne de Hamilton, une communauté unie dans la culture et la solidarité.',
    'footer-copy': '© 2026 AHH | Association Haïtienne de Hamilton. Tous droits réservés.',
    'casl.text': '🍪 Ce site utilise des témoins (cookies) essentiels à son fonctionnement, conformément à la <strong>Loi canadienne anti-pourriel (LCAP/CASL)</strong>. En continuant à naviguer, vous acceptez notre <a href="/privacy.html">politique de confidentialité</a>.',
    'casl.accept': 'Accepter',
    'casl.decline': 'Refuser',
  },

  en: {
    // ── index.html ─────────────────────────────────────────────────────────
    'hero.badge': 'Haitian Community · Hamilton, ON',
    'hero.intro': 'Our community is built on essential values:',
    'hero.values': 'Freedom · Equality · Solidarity',
    'hero.subtitle': 'and unity as the source of our strength.',
    'hero.sub': "Hand in hand, let's create the place we always hoped for.",
    'hero.btn1': 'See our activities',
    'hero.btn2': 'Join us',
    'stat.membres': 'Active Members',
    'stat.activites': 'Activities',
    'stat.benevoles': 'Volunteer Hours',
    'stat.annees': 'Years of Service',
    'why.badge': 'Benefits',
    'why.h2': 'Why join AHH?',
    'why1.h3': 'Community Network',
    'why1.p': 'Connect with Haitian families from Hamilton and the surrounding area.',
    'why2.h3': 'Culture & Traditions',
    'why2.p': 'Celebrate the richness of Haitian culture through our events and activities.',
    'why3.h3': 'Opportunities',
    'why3.p': 'Access internships, training and job opportunities for the community.',
    'why4.h3': 'Mutual Aid & Support',
    'why4.p': 'Benefit from a support network for new families arriving in Canada.',
    'members.join1': 'Join',
    'members.join2': 'active members of the AHH community',
    'members.cta': 'Join us →',
    'cd.next': 'Next event:',
    'cd.days': 'days',
    'cd.hours': 'hours',
    'cd.min': 'min',
    'cd.sec': 'sec',
    'welcome.h2': 'Welcome to the AHH community!',
    'welcome.p1': 'Haitian Association of Hamilton: culture, solidarity and mutual aid since 2008.',
    'welcome.p2': 'Join our growing community. Access activities, cultural events and the Haitian-Canadian support network.',
    'welcome.btn1': 'Become a member →',
    'welcome.btn2': 'Explore the site',
    'featured.badge': '⭐ FEATURED',
    'link.allActivities': 'See all activities →',
    'feed.badge': 'Live',
    'feed.h2': 'Upcoming activities',
    'feed.p': "Stay connected to your community's events.",
    'galprev.badge': 'Gallery',
    'galprev.h2': 'Our best moments',
    'galprev.p': 'A window into the life and culture of our community.',
    'galprev.link': 'See the full gallery →',
    'videos.badge': 'Our videos',
    'videos.h2': 'Relive our moments',
    'videos.p': 'Discover our events and activities on video.',
    'sponsors.badge': 'Partners',
    'sponsors.h2': 'Our sponsors',
    'sponsors.p': "Thank you to those who support the mission of the Haitian Association of Hamilton.",
    'don.badge': 'Support AHH',
    'don.h2': 'Contribute to our mission',
    'don.p': 'Your donation funds our activities, supports families and celebrates Haitian culture in Hamilton.',
    'don.toggle': '🔄 Monthly donation',
    'don.label1': 'Friend',
    'don.desc1': 'Covers the cost of a community activity.',
    'don.give10': 'Give $10',
    'don.popular': 'Popular',
    'don.label2': 'Benefactor',
    'don.desc2': 'Supports a family settling in Hamilton.',
    'don.give50': 'Give $50',
    'don.label3': 'Partner',
    'don.desc3': 'Sponsors a cultural event or community project.',
    'don.give100': 'Give $100',
    'don.label4': 'Custom amount',
    'don.desc4': 'Choose the amount that suits you. Every dollar counts!',
    'don.giveGeneric': 'Give',
    'don.giveAmount': 'Give $',
    'don.toggleActive': '✅ Monthly mode active, click to return to a one-time donation',
    'don.monthlyAmount': 'Monthly donation $',
    'don.perMonth': '/month',
    'don.minAmount': 'Please enter a minimum amount of $1.',
    'don.emailPrompt': 'Your email (optional):',
    'don.error': 'Error',
    'don.connError': 'Connection error',
    'amb.badge': '⭐ Honor',
    'amb.h2': 'Ambassador <span class="italic-accent">of the month</span>',
    'amb.p': 'Every month, we celebrate an outstanding member of our community.',
    'amb.crown': '👑 Ambassador of the month',
    'tl.badge': 'Our history',
    'tl.h2': 'AHH since <span class="italic-accent-blue">2008</span>',
    'tl.p': "More than 17 years of solidarity, culture and commitment to the Haitian community of Hamilton.",
    'tl1.h4': 'Founding of AHH',
    'tl1.p': 'A group of Haitian families in Hamilton comes together to create a community association rooted in the values of mutual aid and solidarity.',
    'tl2.h4': 'First major cultural events',
    'tl2.p': 'Organization of the first Haitian cultural evenings in Hamilton, celebrating music, cuisine and the traditions of the Haitian people.',
    'tl3.h4': 'Newcomer assistance program',
    'tl3.p': 'Launch of a structured integration support program for Haitian families newly arrived in Canada.',
    'tl4.h4': 'Digital transition',
    'tl4.p': "Facing the pandemic, AHH innovates by moving its activities online, strengthening community ties despite the distance.",
    'tl5.h4': 'AHH digital platform',
    'tl5.p': 'Launch of the complete online platform: member management, events, tickets, payments and communications — a first in the region.',
    'tl6.h4': 'Growth and outreach',
    'tl6.p': 'AHH keeps growing, innovating and reaching further, with a community more united than ever around Haitian and Canadian values.',
    'info.badge': '🇭🇹 Haiti',
    'info.h2': 'Haiti in numbers',
    'info.p': 'The Pearl of the Antilles, a nation rich in history, culture and resilience.',
    'info1.label': "First independent Black republic in the world",
    'info2.label': 'Inhabitants on the island',
    'info3.label': 'Official languages: French and Haitian Creole',
    'info4.label': 'Years of musical history (Rara, Kompa, Jazz)',
    'info5.label': 'National dish: fried pork served with banann peze',
    'info6.label': 'Year the blue and red Haitian flag was created',
    'faq.badge': 'Frequently asked questions',
    'faq.h2': 'Everything you want to <span class="highlight">know</span>',
    'faq.p': 'Answers to the most common questions about AHH.',
    'faq1.q': 'How do I become an AHH member?',
    'faq1.a': 'You can become a member by filling out our <a href="adhesion.html" style="color:var(--g2);font-weight:600">online membership form</a>. Membership is open to anyone interested in the Haitian community of Hamilton. A confirmation email will be sent to you after approval.',
    'faq2.q': 'What is the cost of annual membership?',
    'faq2.a': 'Membership cost varies by plan. We offer a free basic plan, as well as Benefactor and Partner plans for those who want to support our activities further. All details are on the membership page.',
    'faq3.q': 'How do I register for an activity or event?',
    'faq3.a': 'Check out our <a href="actualites.html" style="color:var(--g2);font-weight:600">activities page</a> and click on the event you\'re interested in. If the event has a fee, you can purchase your tickets directly online through our secure Stripe payment system.',
    'faq4.q': 'How do I make a donation to the association?',
    'faq4.a': 'You can donate directly from our <a href="#don" style="color:var(--g2);font-weight:600">Donations section</a> at the bottom of the home page. We accept secure online payments via Stripe. Every contribution, small or large, helps our community grow.',
    'faq5.q': "I'm a newly arrived Haitian in Hamilton — how can AHH help me?",
    'faq5.a': 'AHH offers a support program for newcomers: orientation, integration resources, access to the community network and administrative support. Contact us via our <a href="#contact" style="color:var(--g2);font-weight:600">contact form</a> or by phone.',
    'faq6.q': 'How do I join the AHH WhatsApp group?',
    'faq6.a': 'Click the green WhatsApp button at the bottom right of the page, or contact Jean Raymond Antoine directly at 905-519-7967. The group is open to all active members of the Haitian community of Hamilton.',
    'nl.h2': 'Stay informed',
    'nl.p': 'Receive our news, invitations and announcements directly in your inbox. Free, ad-free.',
    'nl.placeholder': 'your@email.com',
    'nl.btn': 'Subscribe',
    'nl.invalidEmail': 'Please enter a valid email.',
    'nl.success': 'Subscription confirmed! Thank you for joining our community.',
    'nl.error': 'Error. Please try again.',
    'contact.badge': 'Contact',
    'contact.h2': 'Write to us',
    'contact.p': "We're happy to welcome you. Contact us with any questions.",
    'contact.address': 'Address',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'cf.title': 'Send us a message',
    'cf.sentH3': 'Message sent!',
    'cf.sentP': "Thank you for contacting us. We'll reply as soon as possible.",
    'cf.name': 'Full name',
    'cf.email': 'Email',
    'cf.subject': 'Subject',
    'cf.subject.choose': 'Choose a subject…',
    'cf.subject.general': 'General information',
    'cf.subject.adhesion': 'Membership',
    'cf.subject.benevolat': 'Volunteering',
    'cf.subject.evenements': 'Events',
    'cf.subject.partenariat': 'Partnership',
    'cf.subject.autre': 'Other',
    'cf.adhesionNotice': 'To become an AHH member, use our dedicated form:<a href="adhesion.html" style="color:#1b5e20;font-weight:700;display:block;margin-top:6px">→ Membership form</a>',
    'cf.message': 'Message',
    'cf.message.placeholder': 'How can we help you?',
    'cf.submit': 'Send message',
    'cf.privacyNote': 'Your data is processed according to our <a href="privacy.html" style="color:var(--g2)">privacy policy</a>.',
    'cf.sending': 'Sending…',
    'cf.serverError': 'Server error',
    'cf.sendError': 'Error sending message.',
    'cf.fillRequired': 'Please fill in all required fields.',
    'bday.today': 'Today',
    'bday.h2': 'Happy birthday!',
    'bday.p': 'The whole AHH family wishes you a wonderful celebration 🥳',
    'pillars.badge': 'Our Mission',
    'pillars.h2': 'Three pillars that unite us',
    'pillars.desc': 'AHH is built on:',
    'pillar1.h3': 'Networking & Connections',
    'pillar1.p': 'Creating meeting spaces so Haitian families in Hamilton can connect, share and build lasting bonds.',
    'pillar1.link': 'See activities →',
    'pillar2.h3': 'Cultural Events',
    'pillar2.p': 'Organizing vibrant events to celebrate the richness of Haitian culture and strengthen our common identity.',
    'pillar2.link': 'See gallery →',
    'pillar3.h3': 'Assistance Programs',
    'pillar3.p': 'Providing tailored support to Haitian families — newcomers, integration resources and solidarity network.',
    'pillar3.link': 'Join AHH →',
    'test.badge': 'Testimonials',
    'test.h2': 'What our community says',
    'team.badge': 'Leadership',
    'team.h2': 'Our leadership team',
    'team.p': 'Dedicated volunteers serving the community since January 2008.',
    'Présidente': 'President',
    'Vice-Président': 'Vice-President',
    'Trésorière': 'Treasurer',
    'Secrétaire': 'Secretary',
    'Délégué': 'Accompanier',
    'Conseiller': 'Advisor',

    // ── about.html ─────────────────────────────────────────────────────────
    'about.h1': 'About AHH',
    'about.p1': 'Our history, mission and the values that have driven us since our founding in January 2008.',
    'about.who.badge': 'Who we are',
    'about.who.h2': 'An association serving the Haitian community',
    'about.mission.badge': 'Mission & Values',
    'about.mission.h2': 'What guides us',
    'about.mission.p': 'Our mission rests on three fundamental pillars and values rooted in our Haitian identity.',
    'val.liberte.h3': 'Freedom',
    'val.egalite.h3': 'Equality',
    'val.entraide.h3': 'Solidarity',
    'val.culture.h3': 'Culture',
    'val.resilience.h3': 'Resilience',
    'val.espoir.h3': 'Hope',
    'about.hist.badge': 'Our history',
    'about.hist.h2': '17 years of growth and commitment',
    'tl.2009.title': 'AHH Founded',
    'tl.2010.title': 'First years — Building foundations',
    'tl.2014.title': 'Growth and structuring',
    'tl.2018.title': 'Community expansion',
    'tl.2022.title': 'Outreach and recognition',
    'tl.2026.title': '✨ Today — 17 years of commitment',
    'about.part.badge': 'Partners',
    'about.part.h2': 'Those who support us',
    'about.part.p': 'AHH collaborates with local organizations sharing our values of inclusion and community support.',
    'Devenir partenaire →': 'Become a partner →',

    // ── adhesion.html ──────────────────────────────────────────────────────
    'adh.h1': 'Join AHH',
    'adh.p1': 'Become a member and be part of a united, active and caring community.',
    'adh.plans.badge': 'Membership',
    'adh.plans.h2': 'Choose your membership',
    'adh.plans.p': 'All plans include access to activities and belonging to our community.',
    'mem.free.period': 'Basic members',
    'mem.free.btn': 'Join for free',
    'mem.bien.badge': 'Most popular',
    'mem.bien.period': 'per month · $100/year',
    'mem.bien.btn': 'Become a benefactor',
    'mem.part.period': 'per month · $200/year',
    'mem.part.btn': 'Become a partner',
    'adh.form.badge': 'Registration',
    'adh.form.h2': 'Fill out your membership application',
    'adh.form.h3': 'Membership form',
    'Prénom *': 'First name *',
    'Nom *': 'Last name *',
    'Adresse courriel *': 'Email address *',
    'Téléphone': 'Phone',
    'Date de naissance': 'Date of birth',
    'Adresse': 'Address',
    "Type d'adhésion *": 'Membership type *',
    'Comment avez-vous connu AHH ?': 'How did you hear about AHH?',
    'Message (facultatif)': 'Message (optional)',
    "Envoyer ma demande d'adhésion": 'Send my membership application',
    'step1.title': 'Fill out the form',
    'step2.title': 'Email confirmation',
    'step3.title': 'Welcome to the community!',

    // ── actualites.html ────────────────────────────────────────────────────
    'act.h1': 'Activities & Events',
    'act.p1': 'Discover our upcoming gatherings and relive our past moments.',
    'act.upcoming.badge': 'Coming up',
    'act.upcoming.h2': 'Upcoming events',
    'act.upcoming.p': 'Join us for these moments of sharing, culture and solidarity.',
    'act.past.badge': 'Archives',
    'act.past.h2': 'Past events',
    'act.cta.h2': 'Want to participate?',
    'act.cta.p': 'Sign up as a member to register for our events and access the member portal.',
    'act.cta.btn': 'Become a member',
    'Tous': 'All',
    'Culturel': 'Cultural',
    'Bénévolat': 'Volunteer',
    'Réunion': 'Meeting',
    'Sport': 'Sport',
    'Aucun événement trouvé': 'No events found',

    // ── galerie.html ───────────────────────────────────────────────────────
    'gal.h1': 'Our moments together',
    'gal.p1': 'Precious memories of our gatherings, celebrations and community activities.',
    'gal.badge': 'Our photos',
    'gal.h2': 'Community gallery',
    'gal.desc': 'Each image tells the story of a united, vibrant and radiant community.',
    'gal.recent.h3': '📸 Recent photos',
    'gal.recent.p': 'Our latest activities and events',
    'gal.archive.h3': '🏛️ Archives',
    'gal.archive.p': 'Historical photos of our activities',

    // ── talents.html ───────────────────────────────────────────────────────
    'tal.h1': 'Our community talents',
    'tal.p1': 'Discover the professionals and artisans of the Haitian community in Hamilton.',
    'tal.cta.h2': 'Are you a professional?',
    'tal.cta.p': 'Share your expertise with the community. Create your talent listing in the member portal.',
    'tal.cta.btn': 'Create my listing',
    'Construction': 'Construction',
    'Technologie': 'Technology',
    'Cuisine': 'Cooking',
    'Art & Musique': 'Art & Music',
    'Santé': 'Health',
    'Éducation': 'Education',
    'Aucun talent trouvé': 'No talent found',
    'Rechercher un talent…': 'Search for a talent…',

    // ── annonces.html ──────────────────────────────────────────────────────
    'ann.h1': 'Classifieds',
    'ann.p1': 'Buy, sell, donate or exchange within the community.',
    'ann.cta.h2': 'Want to post a listing?',
    'ann.cta.p': 'Members can post their listings from the member portal. Join us!',
    'ann.cta.btn': 'Become a member',
    'Vente': 'Sale',
    'Don': 'Donation',
    'Échange': 'Exchange',
    'Recherche': 'Wanted',
    'Aucune annonce trouvée': 'No listings found',
    'Rechercher une annonce…': 'Search listings…',
    'Gratuit': 'Free',
    'casl.text': '🍪 This site uses cookies essential to its operation, in accordance with Canada\'s Anti-Spam Legislation (<strong>CASL</strong>). By continuing to browse, you accept our <a href="/privacy.html">privacy policy</a>.',
    'casl.accept': 'Accept',
    'casl.decline': 'Decline',
  },

  ht: {
    // ── index.html ─────────────────────────────────────────────────────────
    'hero.badge': 'Kominote Ayisyen · Hamilton, ON',
    'hero.intro': 'Kominote nou an chita sou valè esansyèl yo :',
    'hero.values': 'Libète · Egalite · Solidarite',
    'hero.subtitle': 'ak inite kòm sous fòs nou.',
    'hero.sub': 'Men nan men, ann kreye kote nou te toujou reve a.',
    'hero.btn1': 'Wè aktivite nou yo',
    'hero.btn2': 'Vin jwenn nou',
    'stat.membres': 'Manm aktif',
    'stat.activites': 'Aktivite',
    'stat.benevoles': 'Èdtan bènevolat',
    'stat.annees': 'Ane sèvis',
    'why.badge': 'Avantaj',
    'why.h2': 'Poukisa vin jwenn AHH ?',
    'why1.h3': 'Rezo kominotè',
    'why1.p': 'Konekte ak fanmi ayisyen Hamilton ak rejyon an.',
    'why2.h3': 'Kilti & tradisyon',
    'why2.p': 'Selebre richès kilti ayisyen an atravè evènman ak aktivite nou yo.',
    'why3.h3': 'Opòtinite',
    'why3.p': 'Jwenn aksè a estaj, fòmasyon ak ofri travay pou kominote a.',
    'why4.h3': 'Antrèd & sipò',
    'why4.p': 'Benefisye yon rezo antrèd pou nouvo fanmi k ap rive nan Kanada.',
    'members.join1': 'Vin jwenn',
    'members.join2': 'manm aktif nan kominote AHH la',
    'members.cta': 'Vin jwenn nou →',
    'cd.next': 'Pwochen evènman :',
    'cd.days': 'jou',
    'cd.hours': 'è',
    'cd.min': 'min',
    'cd.sec': 'sek',
    'welcome.h2': 'Byenveni nan kominote AHH la !',
    'welcome.p1': 'Asosyasyon Ayisyen Hamilton : kilti, solidarite ak antrèd depi 2008.',
    'welcome.p2': 'Vin jwenn kominote nou k ap grandi a. Jwenn aksè a aktivite, evènman kiltirèl ak rezo antrèd ayisyen-kanadyen an.',
    'welcome.btn1': 'Vin manm →',
    'welcome.btn2': 'Eksplore sit la',
    'featured.badge': '⭐ AN VEDÈT',
    'link.allActivities': 'Wè tout aktivite yo →',
    'feed.badge': 'An dirèk',
    'feed.h2': 'Pwochen aktivite yo',
    'feed.p': 'Rete konekte ak evènman kominote w la.',
    'galprev.badge': 'Galri',
    'galprev.h2': 'Pi bèl moman nou yo',
    'galprev.p': 'Yon fenèt sou lavi ak kilti kominote nou an.',
    'galprev.link': 'Wè tout galri a →',
    'videos.badge': 'Videyo nou yo',
    'videos.h2': 'Reviv moman nou yo',
    'videos.p': 'Dekouvri evènman ak aktivite nou yo an videyo.',
    'sponsors.badge': 'Patnè',
    'sponsors.h2': 'Konmanditè nou yo',
    'sponsors.p': 'Mèsi a tout moun ki soutni misyon Asosyasyon Ayisyen Hamilton an.',
    'don.badge': 'Soutni AHH',
    'don.h2': 'Kontribye nan misyon nou an',
    'don.p': 'Don ou finanse aktivite nou yo, soutni fanmi yo epi fè kilti ayisyen an briye Hamilton.',
    'don.toggle': '🔄 Don chak mwa',
    'don.label1': 'Zanmi',
    'don.desc1': 'Kouvri frè yon aktivite kominotè.',
    'don.give10': 'Bay $10',
    'don.popular': 'Popilè',
    'don.label2': 'Byenfetè',
    'don.desc2': 'Soutni yon fanmi k ap enstale Hamilton.',
    'don.give50': 'Bay $50',
    'don.label3': 'Patnè',
    'don.desc3': 'Sponsò yon evènman kiltirèl oswa yon pwojè kominotè.',
    'don.give100': 'Bay $100',
    'don.label4': 'Montan lib',
    'don.desc4': 'Chwazi montan ki fè w plezi. Chak dola konte !',
    'don.giveGeneric': 'Bay',
    'don.giveAmount': 'Bay $',
    'don.toggleActive': '✅ Mòd chak mwa aktif, klike pou retounen nan don inik',
    'don.monthlyAmount': 'Don chak mwa $',
    'don.perMonth': '/mwa',
    'don.minAmount': 'Tanpri antre yon montan minimòm 1$.',
    'don.emailPrompt': 'Imèl ou (opsyonèl) :',
    'don.error': 'Erè',
    'don.connError': 'Erè koneksyon',
    'amb.badge': '⭐ Onè',
    'amb.h2': 'Anbasadè <span class="italic-accent">mwa a</span>',
    'amb.p': 'Chak mwa, nou selebre yon manm ekstraòdinè nan kominote nou an.',
    'amb.crown': '👑 Anbasadè mwa a',
    'tl.badge': 'Istwa nou',
    'tl.h2': 'AHH depi <span class="italic-accent-blue">2008</span>',
    'tl.p': 'Plis pase 17 ane solidarite, kilti ak angajman nan sèvis kominote ayisyen Hamilton an.',
    'tl1.h4': 'Fondasyon AHH',
    'tl1.p': 'Yon gwoup fanmi ayisyen Hamilton reyini pou kreye yon asosyasyon kominotè ki chita sou valè antrèd ak solidarite.',
    'tl2.h4': 'Premye gwo evènman kiltirèl yo',
    'tl2.p': 'Òganizasyon premye sware kiltirèl ayisyen Hamilton, ki selebre mizik, kwizin ak tradisyon pèp ayisyen an.',
    'tl3.h4': 'Pwogram asistans pou nouvo arivan yo',
    'tl3.p': 'Lansman yon pwogram estriktire pou ede fanmi ayisyen ki fenk rive Kanada entegre.',
    'tl4.h4': 'Tranzisyon nimerik',
    'tl4.p': 'Fas ak pandemi an, AHH inove lè li òganize aktivite li yo an liy, sa ki ranfòse lyen kominotè yo malgre distans lan.',
    'tl5.h4': 'Platfòm nimerik AHH',
    'tl5.p': 'Lansman platfòm konplè sou entènèt la : jesyon manm, evènman, tikè, peman ak kominikasyon, yon premye nan rejyon an.',
    'tl6.h4': 'Kwasans ak rayonnman',
    'tl6.p': 'AHH kontinye grandi, inove ak briye, ak yon kominote ki pi ini pase janm sou valè ayisyen ak kanadyen yo.',
    'info.badge': '🇭🇹 Ayiti',
    'info.h2': 'Ayiti an chif',
    'info.p': 'Bijou Antiy yo, yon nasyon ki rich an istwa, kilti ak rezistans.',
    'info1.label': 'Premye repiblik nwa endepandan nan mond lan',
    'info2.label': 'Popilasyon sou zile a',
    'info3.label': 'Lang ofisyèl yo : franse ak kreyòl ayisyen',
    'info4.label': 'Ane istwa mizikal (Rara, Konpa, Djaz)',
    'info5.label': 'Manje nasyonal : vyann kochon fri ak bannann peze',
    'info6.label': 'Ane drapo ble ak wouj ayisyen an te kreye',
    'faq.badge': 'Kesyon moun poze souvan',
    'faq.h2': 'Tout sa w vle <span class="highlight">konnen</span>',
    'faq.p': 'Repons a kesyon moun poze pi souvan sou AHH.',
    'faq1.q': 'Kijan pou m vin manm AHH ?',
    'faq1.a': 'Ou ka vin manm lè w ranpli <a href="adhesion.html" style="color:var(--g2);font-weight:600">fòm adezyon anliy nou an</a>. Adezyon an ouvè pou tout moun ki enterese nan kominote ayisyen Hamilton an. Y ap voye yon imèl konfimasyon ba ou apre apwobasyon.',
    'faq2.q': 'Konbyen kotizasyon anyèl la koute ?',
    'faq2.a': 'Kotizasyon an varye selon plan ou chwazi a. Nou ofri yon plan gratis debaz, ansanm ak plan Byenfetè ak Patnè pou moun ki vle soutni aktivite nou yo plis. Tout detay yo sou paj adezyon an.',
    'faq3.q': 'Kijan pou m enskri nan yon aktivite oswa evènman ?',
    'faq3.a': 'Gade <a href="actualites.html" style="color:var(--g2);font-weight:600">paj aktivite</a> nou an epi klike sou evènman ki enterese w la. Si evènman an peye, ou ka achte tikè w yo dirèkteman anliy atravè sistèm peman sekirize Stripe nou an.',
    'faq4.q': 'Kijan pou m fè yon don bay asosyasyon an ?',
    'faq4.a': 'Ou ka fè yon don dirèkteman nan <a href="#don" style="color:var(--g2);font-weight:600">seksyon Don</a> anba paj akèy la. Nou aksepte peman sekirize anliy atravè Stripe. Chak kontribisyon, piti oswa gwo, ede kominote nou an grandi.',
    'faq5.q': 'Mwen se yon nouvo arivan ayisyen Hamilton, kijan AHH ka ede m ?',
    'faq5.a': 'AHH ofri yon pwogram akonpayman pou nouvo arivan yo : oryantasyon, resous entegrasyon, aksè nan rezo kominotè a ak sipò administratif. Kontakte nou atravè <a href="#contact" style="color:var(--g2);font-weight:600">fòm kontak</a> nou an oswa pa telefòn.',
    'faq6.q': 'Kijan pou m antre nan gwoup WhatsApp AHH la ?',
    'faq6.a': 'Klike sou bouton WhatsApp vèt anba adwat paj la, oswa kontakte Jean Raymond Antoine dirèkteman nan 905-519-7967. Gwoup la ouvè pou tout manm aktif kominote ayisyen Hamilton an.',
    'nl.h2': 'Rete enfòme',
    'nl.p': 'Resevwa nouvèl, envitasyon ak anons nou yo dirèkteman nan bwat imèl ou. Gratis, san piblisite.',
    'nl.placeholder': 'imèl@ou.com',
    'nl.btn': 'Abòne',
    'nl.invalidEmail': 'Tanpri antre yon imèl valid.',
    'nl.success': 'Abònman konfime ! Mèsi pou w vin jwenn kominote nou an.',
    'nl.error': 'Erè. Tanpri eseye ankò.',
    'contact.badge': 'Kontak',
    'contact.h2': 'Ekri nou',
    'contact.p': 'Nou kontan resevwa w. Kontakte nou pou nenpòt kesyon.',
    'contact.address': 'Adrès',
    'contact.phone': 'Telefòn',
    'contact.email': 'Imèl',
    'cf.title': 'Voye yon mesaj ba nou',
    'cf.sentH3': 'Mesaj voye !',
    'cf.sentP': 'Mèsi paske w kontakte nou. N ap reponn ou pi vit posib.',
    'cf.name': 'Non konplè',
    'cf.email': 'Imèl',
    'cf.subject': 'Sijè',
    'cf.subject.choose': 'Chwazi yon sijè…',
    'cf.subject.general': 'Enfòmasyon jeneral',
    'cf.subject.adhesion': 'Adezyon',
    'cf.subject.benevolat': 'Benevola',
    'cf.subject.evenements': 'Evènman',
    'cf.subject.partenariat': 'Patenarya',
    'cf.subject.autre': 'Lòt',
    'cf.adhesionNotice': 'Pou vin manm AHH, itilize fòm dedye nou an :<a href="adhesion.html" style="color:#1b5e20;font-weight:700;display:block;margin-top:6px">→ Fòm adezyon</a>',
    'cf.message': 'Mesaj',
    'cf.message.placeholder': 'Kijan nou ka ede w ?',
    'cf.submit': 'Voye mesaj la',
    'cf.privacyNote': 'Done ou yo trete selon <a href="privacy.html" style="color:var(--g2)">politik konfidansyalite</a> nou an.',
    'cf.sending': 'Voye ap fèt…',
    'cf.serverError': 'Erè sèvè',
    'cf.sendError': 'Erè pandan l ap voye.',
    'cf.fillRequired': 'Tanpri ranpli tout chan obligatwa yo.',
    'bday.today': 'Jodi a',
    'bday.h2': 'Bòn fèt !',
    'bday.p': 'Gran fanmi AHH la swete w yon bèl fèt 🥳',
    'pillars.badge': 'Misyon nou',
    'pillars.h2': 'Twa poto ki ini nou',
    'pillars.desc': 'AHH chita sou :',
    'pillar1.h3': 'Rezo & Koneksyon',
    'pillar1.p': 'Kreye espas rankont pou fanmi ayisyen nan Hamilton ka konekte, pataje ak bati lyen dirab.',
    'pillar1.link': 'Wè aktivite yo →',
    'pillar2.h3': 'Evènman kiltirèl',
    'pillar2.p': 'Òganize evènman vibran pou selebre richès kilti ayisyen an ak ranfòse idantite nou ansanm.',
    'pillar2.link': 'Wè galri a →',
    'pillar3.h3': 'Pwogram asistans',
    'pillar3.p': 'Bay sipò adapte pou fanmi ayisyen yo — nouvo rive, resous entegrasyon ak rezo solidarite.',
    'pillar3.link': 'Vin jwenn AHH →',
    'test.badge': 'Temwayaj',
    'test.h2': 'Sa kominote nou an di',
    'team.badge': 'Lidèchip',
    'team.h2': 'Ekip lidèchip nou an',
    'team.p': 'Bènèvòl angaje nan sèvis kominote a depi 2009.',
    'Présidente': 'Prezidante',
    'Vice-Président': 'Vis-Prezidan',
    'Trésorière': 'Trezorye',
    'Secrétaire': 'Sekretè',
    'Délégué': 'Akonpanatè',
    'Accompagnateur': 'Akonpanatè',
    'Conseiller': 'Konseye',

    // ── about.html ─────────────────────────────────────────────────────────
    'about.h1': 'Sou AHH',
    'about.p1': 'Istwa nou, misyon nou ak valè ki gide nou depi fondayson nou an an 2009.',
    'about.who.badge': 'Ki nou ye',
    'about.who.h2': 'Yon asosyasyon nan sèvis kominote ayisyen an',
    'about.mission.badge': 'Misyon & Valè',
    'about.mission.h2': 'Sa ki gide nou',
    'about.mission.p': 'Misyon nou repoze sou twa poto fondamantal ak valè ki anrasinen nan idantite ayisyen nou.',
    'val.liberte.h3': 'Libète',
    'val.egalite.h3': 'Egalite',
    'val.entraide.h3': 'Solidarite',
    'val.culture.h3': 'Kilti',
    'val.resilience.h3': 'Rezilyans',
    'val.espoir.h3': 'Espwa',
    'about.hist.badge': 'Istwa nou',
    'about.hist.h2': '17 ane kwasans ak angajman',
    'tl.2009.title': 'Fondayson AHH',
    'tl.2010.title': 'Premye ane — Bati fondasyon yo',
    'tl.2014.title': 'Kwasans ak estriktirasyon',
    'tl.2018.title': 'Ekspansyon kominotè',
    'tl.2022.title': 'Rayonnman ak rekonesans',
    'tl.2026.title': '✨ Jodi a — 17 ane angajman',
    'about.part.badge': 'Patnè',
    'about.part.h2': 'Moun ki sipòte nou',
    'about.part.p': 'AHH kolabore ak òganizasyon lokal ki pataje valè nou yo sou enklizyon ak sipò kominotè.',
    'Devenir partenaire →': 'Vin patnè →',

    // ── adhesion.html ──────────────────────────────────────────────────────
    'adh.h1': 'Vin jwenn AHH',
    'adh.p1': 'Vin manm epi fè pati yon kominote ini, aktif ak atansyone.',
    'adh.plans.badge': 'Manmbachip',
    'adh.plans.h2': 'Chwazi manmbachip ou',
    'adh.plans.p': 'Tout plan yo enkli aksè nan aktivite yo ak apartenans nan kominote nou an.',
    'mem.free.period': 'Manm debaz',
    'mem.free.btn': 'Vin manm gratis',
    'mem.bien.badge': 'Pi popilè',
    'mem.bien.period': 'pa mwa · $100/ane',
    'mem.bien.btn': 'Vin bienfektè',
    'mem.part.period': 'pa mwa · $200/ane',
    'mem.part.btn': 'Vin patnè',
    'adh.form.badge': 'Enskripsyon',
    'adh.form.h2': 'Ranpli aplikasyon manmbachip ou',
    'adh.form.h3': 'Fòm manmbachip',
    'Prénom *': 'Prenon *',
    'Nom *': 'Non *',
    'Adresse courriel *': 'Adrès imèl *',
    'Téléphone': 'Telefòn',
    'Date de naissance': 'Dat nesans',
    'Adresse': 'Adrès',
    "Type d'adhésion *": 'Tip manmbachip *',
    'Comment avez-vous connu AHH ?': 'Kijan ou te konnen AHH?',
    'Message (facultatif)': 'Mesaj (opsyonèl)',
    "Envoyer ma demande d'adhésion": 'Voye demann manmbachip mwen',
    'step1.title': 'Ranpli fòm nan',
    'step2.title': 'Konfirmasyon pa imèl',
    'step3.title': 'Byenveni nan kominote a!',

    // ── actualites.html ────────────────────────────────────────────────────
    'act.h1': 'Aktivite & Evènman',
    'act.p1': 'Dekouvri rasanbleman kap vini yo epi reviv moman pase nou yo.',
    'act.upcoming.badge': 'Ap vini',
    'act.upcoming.h2': 'Evènman kap vini',
    'act.upcoming.p': 'Vin jwenn nou pou moman pataj, kilti ak solidarite sa yo.',
    'act.past.badge': 'Achiv',
    'act.past.h2': 'Evènman pase yo',
    'act.cta.h2': 'Ou vle patisipe?',
    'act.cta.p': 'Enskri kòm manm pou ou ka enskri nan evènman nou yo epi jwenn aksè nan pòtal manm nan.',
    'act.cta.btn': 'Vin manm',
    'Tous': 'Tout',
    'Culturel': 'Kiltirèl',
    'Bénévolat': 'Bènèvolat',
    'Réunion': 'Reyinyon',
    'Sport': 'Spò',
    'Aucun événement trouvé': 'Pa gen evènman jwenn',

    // ── galerie.html ───────────────────────────────────────────────────────
    'gal.h1': 'Moman nou ansanm',
    'gal.p1': 'Souvni presye rasanbleman, selebrasyon ak aktivite kominotè nou yo.',
    'gal.badge': 'Foto nou yo',
    'gal.h2': 'Galri kominotè',
    'gal.desc': 'Chak imaj rakonte istwa yon kominote ini, vivan ak rayonnant.',
    'gal.recent.h3': '📸 Foto resan',
    'gal.recent.p': 'Dènye aktivite ak evènman nou yo',
    'gal.archive.h3': '🏛️ Achiv',
    'gal.archive.p': 'Foto istorik aktivite nou yo',

    // ── talents.html ───────────────────────────────────────────────────────
    'tal.h1': 'Talan kominotè nou yo',
    'tal.p1': 'Dekouvri pwofesyonèl ak atisan kominote ayisyen an nan Hamilton.',
    'tal.cta.h2': 'Ou se yon pwofesyonèl?',
    'tal.cta.p': 'Pataje ekspètiz ou ak kominote a. Kreye afi talan ou nan pòtal manm nan.',
    'tal.cta.btn': 'Kreye afi mwen',
    'Construction': 'Konstriksyon',
    'Technologie': 'Teknoloji',
    'Cuisine': 'Kwizin',
    'Art & Musique': 'Art & Mizik',
    'Santé': 'Sante',
    'Éducation': 'Edikasyon',
    'Aucun talent trouvé': 'Pa gen talan jwenn',
    'Rechercher un talent…': 'Chèche yon talan…',

    // ── annonces.html ──────────────────────────────────────────────────────
    'ann.h1': 'Piti anonn',
    'ann.p1': 'Achte, vann, bay oswa echanje nan kominote a.',
    'ann.cta.h2': 'Ou vle pibliye yon anonn?',
    'ann.cta.p': 'Manm yo ka pibliye anonn yo depi nan pòtal manm nan. Vin jwenn nou!',
    'ann.cta.btn': 'Vin manm',
    'Vente': 'Lavant',
    'Don': 'Don',
    'Échange': 'Echanj',
    'Recherche': 'Rechèch',
    'Aucune annonce trouvée': 'Pa gen anonn jwenn',
    'Rechercher une annonce…': 'Chèche anonn…',
    'Gratuit': 'Gratis',
    'casl.text': '🍪 Sit sa a itilize temwen (cookies) ki esansyèl pou fonksyònman li, dapre <strong>Lwa kanadyen kont pouryèl (LCAP/CASL)</strong>. Si w kontinye navige, ou aksepte <a href="/privacy.html">politik konfidansyalite</a> nou an.',
    'casl.accept': 'Aksepte',
    'casl.decline': 'Refize',
  }
};
