window.AHH_T = {
  fr: {
    'hero.badge': '🇭🇹 Communauté Haïtienne · Hamilton, ON',
    'hero.intro': "Notre communauté s'appuie sur des valeurs essentielles :",
    'hero.values': 'Liberté · Égalité · Entraide',
    'hero.subtitle': "et l'union comme source de notre puissance.",
    'hero.sub': "Main dans la main, créons l'endroit que nous avons toujours espéré.",
    'hero.btn1': 'Voir nos activités',
    'hero.btn2': 'Nous rejoindre',
    'stat.membres': 'Membres actifs',
    'stat.activites': 'Activités',
    'stat.benevoles': 'Heures de bénévolat',
    'stat.annees': 'Années de service',
    'pillars.badge': 'Notre mission',
    'pillars.h2': 'Trois piliers qui nous unissent',
    'pillars.desc': 'AHH repose sur :',
    'pillar1.h3': 'Réseautage & Connexions',
    'pillar1.p': 'Créer des espaces de rencontre pour que les familles haïtiennes de Hamilton se connectent, partagent et bâtissent des liens durables.',
    'pillar1.link': 'Voir les activités →',
    'pillar2.h3': 'Événements culturels',
    'pillar2.p': 'Organiser des événements vibrants pour célébrer la richesse de la culture haïtienne et renforcer notre identité commune.',
    'pillar2.link': 'Voir la galerie →',
    'pillar3.h3': "Programmes d'assistance",
    'pillar3.p': "Offrir un soutien adapté aux familles haïtiennes — nouveaux arrivants, ressources d'intégration et réseau de solidarité.",
    'pillar3.link': 'Rejoindre AHH →',
    'test.badge': 'Témoignages',
    'test.h2': 'Ce que dit notre communauté',
    'team.badge': 'Leadership',
    'team.h2': 'Notre équipe dirigeante',
    'team.p': 'Des bénévoles engagés au service de la communauté depuis 2009.',
    'about.h1': "À propos d'AHH",
    'about.p1': 'Notre histoire, notre mission et les valeurs qui nous animent depuis notre fondation en 2009.',
    'about.who.badge': 'Qui sommes-nous',
    'about.who.h2': 'Une association au service de la communauté haïtienne',
    'about.mission.badge': 'Mission & Valeurs',
    'about.mission.h2': 'Ce qui nous guide',
    'about.mission.p': 'Notre mission repose sur trois piliers fondamentaux et des valeurs ancrées dans notre identité haïtienne.',
    'val.liberte.h3': 'Liberté',
    'val.egalite.h3': 'Égalité',
    'val.entraide.h3': 'Entraide',
    'val.culture.h3': 'Culture',
    'val.resilience.h3': 'Résilience',
    'val.espoir.h3': 'Espoir',
    'about.hist.badge': 'Notre histoire',
    'about.hist.h2': "17 ans de croissance et d'engagement",
    'tl.2009.title': "Fondation d'AHH",
    'tl.2010.title': 'Premières années — Construction des bases',
    'tl.2014.title': 'Croissance et structuration',
    'tl.2018.title': 'Expansion communautaire',
    'tl.2022.title': 'Rayonnement et reconnaissance',
    'tl.2026.title': "✨ Aujourd'hui — 17 ans d'engagement",
    'about.part.badge': 'Partenaires',
    'about.part.h2': 'Ceux qui nous soutiennent',
    'about.part.p': "AHH collabore avec des organisations locales partageant nos valeurs d'inclusion et de soutien communautaire.",
    'adh.h1': 'Rejoindre AHH',
    'adh.p1': "Devenez membre et faites partie d'une communauté unie, active et bienveillante.",
    'adh.plans.badge': 'Adhésion',
    'adh.plans.h2': 'Choisissez votre membership',
    'adh.plans.p': "Toutes les formules incluent l'accès aux activités et l'appartenance à notre communauté.",
    'mem.free.period': 'Membres de base',
    'mem.free.btn': 'Adhérer gratuitement',
    'mem.bien.badge': 'Le plus populaire',
    'mem.bien.period': 'par mois · $100/an',
    'mem.bien.btn': 'Devenir bienfaiteur',
    'mem.part.period': 'par mois · $200/an',
    'mem.part.btn': 'Devenir partenaire',
    'adh.form.badge': 'Inscription',
    'adh.form.h2': "Remplissez votre demande d'adhésion",
    'adh.form.h3': "Formulaire d'adhésion",
    'step1.title': 'Remplissez le formulaire',
    'step2.title': 'Confirmation par courriel',
    'step3.title': 'Bienvenue dans la communauté !',
    'act.h1': 'Activités & Événements',
    'act.p1': 'Découvrez nos prochains rassemblements et revivez nos moments passés.',
    'act.upcoming.badge': 'À venir',
    'act.upcoming.h2': 'Prochains événements',
    'act.upcoming.p': 'Rejoignez-nous pour ces moments de partage, culture et solidarité.',
    'act.past.badge': 'Archives',
    'act.past.h2': 'Événements passés',
    'act.cta.h2': 'Vous voulez participer ?',
    'act.cta.p': "Inscrivez-vous comme membre pour vous inscrire à nos événements et accéder au portail membre.",
    'act.cta.btn': 'Devenir membre',
    'gal.h1': 'Nos moments ensemble',
    'gal.p1': 'Des souvenirs précieux de nos rassemblements, célébrations et activités communautaires.',
    'gal.badge': 'Nos photos',
    'gal.h2': 'Galerie communautaire',
    'gal.desc': "Chaque image raconte l'histoire d'une communauté soudée, vivante et rayonnante.",
    'gal.recent.h3': '📸 Photos récentes',
    'gal.recent.p': 'Nos dernières activités et événements',
    'gal.archive.h3': '🏛️ Archives',
    'gal.archive.p': 'Photos historiques de nos activités',
    'tal.h1': 'Nos talents communautaires',
    'tal.p1': 'Découvrez les professionnels et artisans de la communauté haïtienne de Hamilton.',
    'tal.cta.h2': 'Vous êtes un professionnel ?',
    'tal.cta.p': 'Partagez votre expertise avec la communauté. Créez votre fiche talent dans le portail membre.',
    'tal.cta.btn': 'Créer ma fiche',
    'ann.h1': 'Petites annonces',
    'ann.p1': 'Achetez, vendez, donnez ou échangez au sein de la communauté.',
    'ann.cta.h2': 'Vous voulez publier une annonce ?',
    'ann.cta.p': 'Les membres peuvent publier leurs annonces depuis le portail membre. Rejoignez-nous !',
    'ann.cta.btn': 'Devenir membre',
  },

  en: {
    // ── index.html ─────────────────────────────────────────────────────────
    'hero.badge': '🇭🇹 Haitian Community · Hamilton, ON',
    'hero.intro': 'Our community is built on essential values:',
    'hero.values': 'Freedom · Equality · Solidarity',
    'hero.subtitle': 'and unity as the source of our strength.',
    'hero.sub': "Hand in hand, let's create the place we always hoped for.",
    'hero.btn1': 'See our activities',
    'hero.btn2': 'Join us',
    'stat.membres': 'Active Members',
    'stat.activites': 'Activities',
    'stat.benevoles': 'Volunteer Hours',
    'stat.annees': 'Years of Service',
    'pillars.badge': 'Our Mission',
    'pillars.h2': 'Three pillars that unite us',
    'pillars.desc': 'AHH is built on:',
    'pillar1.h3': 'Networking & Connections',
    'pillar1.p': 'Creating meeting spaces so Haitian families in Hamilton can connect, share and build lasting bonds.',
    'pillar1.link': 'See activities →',
    'pillar2.h3': 'Cultural Events',
    'pillar2.p': 'Organizing vibrant events to celebrate the richness of Haitian culture and strengthen our common identity.',
    'pillar2.link': 'See gallery →',
    'pillar3.h3': 'Assistance Programs',
    'pillar3.p': 'Providing tailored support to Haitian families — newcomers, integration resources and solidarity network.',
    'pillar3.link': 'Join AHH →',
    'test.badge': 'Testimonials',
    'test.h2': 'What our community says',
    'team.badge': 'Leadership',
    'team.h2': 'Our leadership team',
    'team.p': 'Dedicated volunteers serving the community since 2009.',
    'Présidente': 'President',
    'Vice-Président': 'Vice-President',
    'Trésorière': 'Treasurer',
    'Secrétaire': 'Secretary',
    'Délégué': 'Delegate',

    // ── about.html ─────────────────────────────────────────────────────────
    'about.h1': 'About AHH',
    'about.p1': 'Our history, mission and the values that have driven us since our founding in 2009.',
    'about.who.badge': 'Who we are',
    'about.who.h2': 'An association serving the Haitian community',
    'about.mission.badge': 'Mission & Values',
    'about.mission.h2': 'What guides us',
    'about.mission.p': 'Our mission rests on three fundamental pillars and values rooted in our Haitian identity.',
    'val.liberte.h3': 'Freedom',
    'val.egalite.h3': 'Equality',
    'val.entraide.h3': 'Solidarity',
    'val.culture.h3': 'Culture',
    'val.resilience.h3': 'Resilience',
    'val.espoir.h3': 'Hope',
    'about.hist.badge': 'Our history',
    'about.hist.h2': '17 years of growth and commitment',
    'tl.2009.title': 'AHH Founded',
    'tl.2010.title': 'First years — Building foundations',
    'tl.2014.title': 'Growth and structuring',
    'tl.2018.title': 'Community expansion',
    'tl.2022.title': 'Outreach and recognition',
    'tl.2026.title': '✨ Today — 17 years of commitment',
    'about.part.badge': 'Partners',
    'about.part.h2': 'Those who support us',
    'about.part.p': 'AHH collaborates with local organizations sharing our values of inclusion and community support.',
    'Devenir partenaire →': 'Become a partner →',

    // ── adhesion.html ──────────────────────────────────────────────────────
    'adh.h1': 'Join AHH',
    'adh.p1': 'Become a member and be part of a united, active and caring community.',
    'adh.plans.badge': 'Membership',
    'adh.plans.h2': 'Choose your membership',
    'adh.plans.p': 'All plans include access to activities and belonging to our community.',
    'mem.free.period': 'Basic members',
    'mem.free.btn': 'Join for free',
    'mem.bien.badge': 'Most popular',
    'mem.bien.period': 'per month · $100/year',
    'mem.bien.btn': 'Become a benefactor',
    'mem.part.period': 'per month · $200/year',
    'mem.part.btn': 'Become a partner',
    'adh.form.badge': 'Registration',
    'adh.form.h2': 'Fill out your membership application',
    'adh.form.h3': 'Membership form',
    'Prénom *': 'First name *',
    'Nom *': 'Last name *',
    'Adresse courriel *': 'Email address *',
    'Téléphone': 'Phone',
    'Date de naissance': 'Date of birth',
    'Adresse': 'Address',
    "Type d'adhésion *": 'Membership type *',
    'Comment avez-vous connu AHH ?': 'How did you hear about AHH?',
    'Message (facultatif)': 'Message (optional)',
    "Envoyer ma demande d'adhésion": 'Send my membership application',
    'step1.title': 'Fill out the form',
    'step2.title': 'Email confirmation',
    'step3.title': 'Welcome to the community!',

    // ── actualites.html ────────────────────────────────────────────────────
    'act.h1': 'Activities & Events',
    'act.p1': 'Discover our upcoming gatherings and relive our past moments.',
    'act.upcoming.badge': 'Coming up',
    'act.upcoming.h2': 'Upcoming events',
    'act.upcoming.p': 'Join us for these moments of sharing, culture and solidarity.',
    'act.past.badge': 'Archives',
    'act.past.h2': 'Past events',
    'act.cta.h2': 'Want to participate?',
    'act.cta.p': 'Sign up as a member to register for our events and access the member portal.',
    'act.cta.btn': 'Become a member',
    'Tous': 'All',
    'Culturel': 'Cultural',
    'Bénévolat': 'Volunteer',
    'Réunion': 'Meeting',
    'Sport': 'Sport',
    'Aucun événement trouvé': 'No events found',

    // ── galerie.html ───────────────────────────────────────────────────────
    'gal.h1': 'Our moments together',
    'gal.p1': 'Precious memories of our gatherings, celebrations and community activities.',
    'gal.badge': 'Our photos',
    'gal.h2': 'Community gallery',
    'gal.desc': 'Each image tells the story of a united, vibrant and radiant community.',
    'gal.recent.h3': '📸 Recent photos',
    'gal.recent.p': 'Our latest activities and events',
    'gal.archive.h3': '🏛️ Archives',
    'gal.archive.p': 'Historical photos of our activities',

    // ── talents.html ───────────────────────────────────────────────────────
    'tal.h1': 'Our community talents',
    'tal.p1': 'Discover the professionals and artisans of the Haitian community in Hamilton.',
    'tal.cta.h2': 'Are you a professional?',
    'tal.cta.p': 'Share your expertise with the community. Create your talent listing in the member portal.',
    'tal.cta.btn': 'Create my listing',
    'Construction': 'Construction',
    'Technologie': 'Technology',
    'Cuisine': 'Cooking',
    'Art & Musique': 'Art & Music',
    'Santé': 'Health',
    'Éducation': 'Education',
    'Aucun talent trouvé': 'No talent found',
    'Rechercher un talent…': 'Search for a talent…',

    // ── annonces.html ──────────────────────────────────────────────────────
    'ann.h1': 'Classifieds',
    'ann.p1': 'Buy, sell, donate or exchange within the community.',
    'ann.cta.h2': 'Want to post a listing?',
    'ann.cta.p': 'Members can post their listings from the member portal. Join us!',
    'ann.cta.btn': 'Become a member',
    'Vente': 'Sale',
    'Don': 'Donation',
    'Échange': 'Exchange',
    'Recherche': 'Wanted',
    'Aucune annonce trouvée': 'No listings found',
    'Rechercher une annonce…': 'Search listings…',
    'Gratuit': 'Free',
  },

  ht: {
    // ── index.html ─────────────────────────────────────────────────────────
    'hero.badge': '🇭🇹 Kominote Ayisyen · Hamilton, ON',
    'hero.intro': 'Kominote nou an chita sou valè esansyèl yo :',
    'hero.values': 'Libète · Egalite · Solidarite',
    'hero.subtitle': 'ak inite kòm sous fòs nou.',
    'hero.sub': 'Men nan men, ann kreye kote nou te toujou reve a.',
    'hero.btn1': 'Wè aktivite nou yo',
    'hero.btn2': 'Vin jwenn nou',
    'stat.membres': 'Manm aktif',
    'stat.activites': 'Aktivite',
    'stat.benevoles': 'Èdtan bènevolat',
    'stat.annees': 'Ane sèvis',
    'pillars.badge': 'Misyon nou',
    'pillars.h2': 'Twa poto ki ini nou',
    'pillars.desc': 'AHH chita sou :',
    'pillar1.h3': 'Rezo & Koneksyon',
    'pillar1.p': 'Kreye espas rankont pou fanmi ayisyen nan Hamilton ka konekte, pataje ak bati lyen dirab.',
    'pillar1.link': 'Wè aktivite yo →',
    'pillar2.h3': 'Evènman kiltirèl',
    'pillar2.p': 'Òganize evènman vibran pou selebre richès kilti ayisyen an ak ranfòse idantite nou ansanm.',
    'pillar2.link': 'Wè galri a →',
    'pillar3.h3': 'Pwogram asistans',
    'pillar3.p': 'Bay sipò adapte pou fanmi ayisyen yo — nouvo rive, resous entegrasyon ak rezo solidarite.',
    'pillar3.link': 'Vin jwenn AHH →',
    'test.badge': 'Temwayaj',
    'test.h2': 'Sa kominote nou an di',
    'team.badge': 'Lidèchip',
    'team.h2': 'Ekip lidèchip nou an',
    'team.p': 'Bènèvòl angaje nan sèvis kominote a depi 2009.',
    'Présidente': 'Prezidante',
    'Vice-Président': 'Vis-Prezidan',
    'Trésorière': 'Trezorye',
    'Secrétaire': 'Sekretè',
    'Délégué': 'Delege',

    // ── about.html ─────────────────────────────────────────────────────────
    'about.h1': 'Sou AHH',
    'about.p1': 'Istwa nou, misyon nou ak valè ki gide nou depi fondayson nou an an 2009.',
    'about.who.badge': 'Ki nou ye',
    'about.who.h2': 'Yon asosyasyon nan sèvis kominote ayisyen an',
    'about.mission.badge': 'Misyon & Valè',
    'about.mission.h2': 'Sa ki gide nou',
    'about.mission.p': 'Misyon nou repoze sou twa poto fondamantal ak valè ki anrasinen nan idantite ayisyen nou.',
    'val.liberte.h3': 'Libète',
    'val.egalite.h3': 'Egalite',
    'val.entraide.h3': 'Solidarite',
    'val.culture.h3': 'Kilti',
    'val.resilience.h3': 'Rezilyans',
    'val.espoir.h3': 'Espwa',
    'about.hist.badge': 'Istwa nou',
    'about.hist.h2': '17 ane kwasans ak angajman',
    'tl.2009.title': 'Fondayson AHH',
    'tl.2010.title': 'Premye ane — Bati fondasyon yo',
    'tl.2014.title': 'Kwasans ak estriktirasyon',
    'tl.2018.title': 'Ekspansyon kominotè',
    'tl.2022.title': 'Rayonnman ak rekonesans',
    'tl.2026.title': '✨ Jodi a — 17 ane angajman',
    'about.part.badge': 'Patnè',
    'about.part.h2': 'Moun ki sipòte nou',
    'about.part.p': 'AHH kolabore ak òganizasyon lokal ki pataje valè nou yo sou enklizyon ak sipò kominotè.',
    'Devenir partenaire →': 'Vin patnè →',

    // ── adhesion.html ──────────────────────────────────────────────────────
    'adh.h1': 'Vin jwenn AHH',
    'adh.p1': 'Vin manm epi fè pati yon kominote ini, aktif ak atansyone.',
    'adh.plans.badge': 'Manmbachip',
    'adh.plans.h2': 'Chwazi manmbachip ou',
    'adh.plans.p': 'Tout plan yo enkli aksè nan aktivite yo ak apartenans nan kominote nou an.',
    'mem.free.period': 'Manm debaz',
    'mem.free.btn': 'Vin manm gratis',
    'mem.bien.badge': 'Pi popilè',
    'mem.bien.period': 'pa mwa · $100/ane',
    'mem.bien.btn': 'Vin bienfektè',
    'mem.part.period': 'pa mwa · $200/ane',
    'mem.part.btn': 'Vin patnè',
    'adh.form.badge': 'Enskripsyon',
    'adh.form.h2': 'Ranpli aplikasyon manmbachip ou',
    'adh.form.h3': 'Fòm manmbachip',
    'Prénom *': 'Prenon *',
    'Nom *': 'Non *',
    'Adresse courriel *': 'Adrès imèl *',
    'Téléphone': 'Telefòn',
    'Date de naissance': 'Dat nesans',
    'Adresse': 'Adrès',
    "Type d'adhésion *": 'Tip manmbachip *',
    'Comment avez-vous connu AHH ?': 'Kijan ou te konnen AHH?',
    'Message (facultatif)': 'Mesaj (opsyonèl)',
    "Envoyer ma demande d'adhésion": 'Voye demann manmbachip mwen',
    'step1.title': 'Ranpli fòm nan',
    'step2.title': 'Konfirmasyon pa imèl',
    'step3.title': 'Byenveni nan kominote a!',

    // ── actualites.html ────────────────────────────────────────────────────
    'act.h1': 'Aktivite & Evènman',
    'act.p1': 'Dekouvri rasanbleman kap vini yo epi reviv moman pase nou yo.',
    'act.upcoming.badge': 'Ap vini',
    'act.upcoming.h2': 'Evènman kap vini',
    'act.upcoming.p': 'Vin jwenn nou pou moman pataj, kilti ak solidarite sa yo.',
    'act.past.badge': 'Achiv',
    'act.past.h2': 'Evènman pase yo',
    'act.cta.h2': 'Ou vle patisipe?',
    'act.cta.p': 'Enskri kòm manm pou ou ka enskri nan evènman nou yo epi jwenn aksè nan pòtal manm nan.',
    'act.cta.btn': 'Vin manm',
    'Tous': 'Tout',
    'Culturel': 'Kiltirèl',
    'Bénévolat': 'Bènèvolat',
    'Réunion': 'Reyinyon',
    'Sport': 'Spò',
    'Aucun événement trouvé': 'Pa gen evènman jwenn',

    // ── galerie.html ───────────────────────────────────────────────────────
    'gal.h1': 'Moman nou ansanm',
    'gal.p1': 'Souvni presye rasanbleman, selebrasyon ak aktivite kominotè nou yo.',
    'gal.badge': 'Foto nou yo',
    'gal.h2': 'Galri kominotè',
    'gal.desc': 'Chak imaj rakonte istwa yon kominote ini, vivan ak rayonnant.',
    'gal.recent.h3': '📸 Foto resan',
    'gal.recent.p': 'Dènye aktivite ak evènman nou yo',
    'gal.archive.h3': '🏛️ Achiv',
    'gal.archive.p': 'Foto istorik aktivite nou yo',

    // ── talents.html ───────────────────────────────────────────────────────
    'tal.h1': 'Talan kominotè nou yo',
    'tal.p1': 'Dekouvri pwofesyonèl ak atisan kominote ayisyen an nan Hamilton.',
    'tal.cta.h2': 'Ou se yon pwofesyonèl?',
    'tal.cta.p': 'Pataje ekspètiz ou ak kominote a. Kreye afi talan ou nan pòtal manm nan.',
    'tal.cta.btn': 'Kreye afi mwen',
    'Construction': 'Konstriksyon',
    'Technologie': 'Teknoloji',
    'Cuisine': 'Kwizin',
    'Art & Musique': 'Art & Mizik',
    'Santé': 'Sante',
    'Éducation': 'Edikasyon',
    'Aucun talent trouvé': 'Pa gen talan jwenn',
    'Rechercher un talent…': 'Chèche yon talan…',

    // ── annonces.html ──────────────────────────────────────────────────────
    'ann.h1': 'Piti anonn',
    'ann.p1': 'Achte, vann, bay oswa echanje nan kominote a.',
    'ann.cta.h2': 'Ou vle pibliye yon anonn?',
    'ann.cta.p': 'Manm yo ka pibliye anonn yo depi nan pòtal manm nan. Vin jwenn nou!',
    'ann.cta.btn': 'Vin manm',
    'Vente': 'Lavant',
    'Don': 'Don',
    'Échange': 'Echanj',
    'Recherche': 'Rechèch',
    'Aucune annonce trouvée': 'Pa gen anonn jwenn',
    'Rechercher une annonce…': 'Chèche anonn…',
    'Gratuit': 'Gratis',
  }
};
